// WFAudit · captura — sniffing (handshake/PMKID) y crackeo
// ======== SNIFFING (captura de handshake) ========
let _hsTimer=null;
async function sniffing(){
  let ifaces=[];
  try{ifaces=await A.ifaces();}catch{}
  setC(`<div class="sup"><div class="g2">
    <div class="card">
      <div class="ctitle">${ic('key')} Sniffing — Captura de Handshake</div>
      <div class="hint">${ic('info',11)}Captura el handshake WPA/WPA2 de 4 vías escuchando la red. Con clientes conectados, el deauth acelera la captura forzando una reconexión. ¿Sin clientes? Prueba <b onclick="goto('advanced')" style="color:var(--c);cursor:pointer">PMKID</b> (panel Avanzado).</div>
      <div class="fgrid"><div class="frow"><label>Interfaz</label><select id="hs-if" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name} (${i.mode})</option>`).join('')}</select></div><div class="frow"><label>Canal</label><input id="hs-ch" class="inp" type="number" value="6"></div></div>
      <div class="frow"><label>BSSID objetivo *</label><input id="hs-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div>
      <div class="frow"><label>ESSID (opcional)</label><input id="hs-essid" class="inp" placeholder="Nombre de la red"></div>
      <div class="fgrid"><div class="frow"><label>Timeout (seg) <span class="tip" data-tip="Tiempo máximo esperando el handshake. Si el AP tiene clientes activos suele bastar 60-120s. Sin clientes, considera usar PMKID (panel Avanzado).">?</span></label><input id="hs-to" class="inp" type="number" value="120"></div><div class="frow"><label>Paquetes deauth <span class="tip" data-tip="Cuántas tramas de desautenticación enviar para forzar la reconexión del cliente. 5-10 suele bastar; más es más ruidoso y detectable.">?</span></label><input id="hs-dp" class="inp" type="number" value="10"></div></div>
      <div class="crow"><input type="checkbox" id="hs-da" checked><label for="hs-da">Enviar deauth antes de capturar</label></div>
      <div style="border:1px solid var(--b0);border-radius:8px;padding:12px;margin:12px 0;background:var(--bg3)">
        <div style="font-size:.66rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin-bottom:9px">${ic('stop',11)} Deauth Manual (bajo demanda)</div>
        <div class="alert aw" style="margin-bottom:9px">${ic('warn')}<div style="font-size:.74rem">Solo en redes propias o con permiso escrito.</div></div>
        <div class="fgrid"><div class="frow"><label>Interfaz</label><select id="da-if" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="frow"><label>BSSID</label><input id="da-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div></div>
        <div class="fgrid"><div class="frow"><label>MAC cliente (vacío=broadcast)</label><input id="da-cli" class="inp" placeholder="FF:FF:FF:FF:FF:FF"></div><div class="frow"><label>Paquetes</label><input id="da-pkts" class="inp" type="number" value="50"></div></div>
        <button class="btn btn-d btn-sm" style="width:100%" onclick="sendDeauth()">${ic('stop')} Enviar Deauth</button>
      </div>
      <button class="btn btn-g" style="width:100%" id="hs-btn" onclick="startHS()">${ic('play')} Capturar Handshake</button>
    </div>
    <div class="card">
      <div class="ctitle">${ic('key')} Resultado</div>
      <div id="hs-cdown" style="display:none"></div>
      <div id="hs-res-empty" class="empty" style="padding:24px">${ic('key',36)}<h3>Sin resultado</h3><p>Inicia una captura</p></div>
      <div id="hs-res" style="display:none"></div>
    </div>
  </div></div>`);}
// ======== CRACK (cualquier captura: handshake o PMKID) ========
async function crack(){
  let caps=[],wls=[];
  try{[caps,wls]=await Promise.all([A.caps(),A.wls()]);}catch{}
  const capArr=Array.isArray(caps)?caps:[];const wlArr=wls?.wordlists||[];
  setC(`<div class="sup"><div class="g2">
    <div class="card">
      <div class="ctitle">${ic('zap')} Crack — Cualquier captura</div>
      <div class="hint">${ic('info',11)}Crackea offline cualquier material capturado: un <b>handshake</b> (de Sniffing o AP-Less) o un <b>PMKID</b>. El tipo se detecta solo por el archivo. Con GPU usa hashcat; si no, aircrack-ng por CPU.</div>
      <div class="frow"><label>Archivo de captura <span class="tip" data-tip="Lista todas las capturas disponibles (handshakes y PMKID). También puedes indicar una ruta manual con «Ruta personalizada».">?</span></label>
        <select id="cr-file" class="inp" onchange="onCrFile()"><option value="">— Selecciona —</option>${capArr.map(c=>{const pk=c.has_pmkid||/\.(22000|16800)$/i.test(c.filename||'');const tag=pk?' ⚡PMKID':(c.has_handshake?' ✓HS':'');return `<option value="${c.filepath}" data-pmkid="${pk?1:0}" data-essid="${(c.target_essid||'').replace(/"/g,'&quot;')}">${c.filename}${c.target_essid?' ('+c.target_essid+')':''}${tag}</option>`;}).join('')}<option value="__custom">Ruta personalizada…</option></select>
        <button class="btn btn-gh btn-xs" style="margin-top:4px" onclick="reloadCrF()">${ic('refresh',11)} Recargar archivos</button>
      </div>
      <div id="cr-cust-file-wrap" style="display:none" class="frow"><label>Ruta del archivo</label><input id="cr-cust-file" class="inp" placeholder="/data/captures/red.cap  ·  /data/pmkid/red.22000"></div>
      <div class="frow"><label>Tipo <span class="tip" data-tip="Auto detecta PMKID (.22000/.16800) frente a handshake por el archivo. Puedes forzarlo si hace falta.">?</span></label>
        <select id="cr-type" class="inp"><option value="auto">Auto (según el archivo)</option><option value="handshake">Handshake (.cap/.pcapng)</option><option value="pmkid">PMKID (.22000)</option></select></div>
      <div class="frow"><label>BSSID objetivo *</label><input id="cr-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div>
      <div class="frow"><label>ESSID <span class="tip" data-tip="Necesario para crackear PMKID (la PMK deriva de la passphrase + SSID). Opcional para handshakes.">?</span></label><input id="cr-essid" class="inp" placeholder="Nombre de la red (para PMKID)"></div>
      <div class="frow"><label>Wordlist</label><select id="cr-wl" class="inp" onchange="{const w=document.getElementById('cr-cust-wl-wrap');if(w)w.style.display=this.value==='__custom'?'block':'none';}"><option value="rockyou.txt">rockyou.txt (clásico)</option>${wlArr.map(w=>`<option value="${w.filename}">${w.filename} (${(w.lines||0).toLocaleString()} líneas)</option>`).join('')}<option value="__custom">Ruta personalizada…</option></select></div>
      <div id="cr-cust-wl-wrap" style="display:none" class="frow"><label>Ruta de la wordlist</label><input id="cr-cust" class="inp" placeholder="/data/wordlists/custom.txt"></div>
      <button class="btn btn-g" style="width:100%;margin-top:6px" id="cr-btn" onclick="startCrack()">${ic('zap')} Iniciar Crack</button>
    </div>
    <div class="card"><div class="ctitle">${ic('zap')} Resultado</div><div id="cr-res" class="empty" style="padding:24px">${ic('zap',36)}<h3>Sin resultado</h3><p>Selecciona una captura y una wordlist</p></div></div>
  </div></div>`);
  onCrFile();}
function onCrFile(){const sel=document.getElementById('cr-file');if(!sel)return;const v=sel.value;const cw=document.getElementById('cr-cust-file-wrap');if(cw)cw.style.display=v==='__custom'?'block':'none';const opt=sel.options[sel.selectedIndex];if(opt&&v&&v!=='__custom'){const es=opt.getAttribute('data-essid');const ee=document.getElementById('cr-essid');if(es&&ee&&!ee.value)ee.value=es;}}
async function reloadCrF(){try{const caps=await A.caps();const sel=document.getElementById('cr-file');if(!sel)return;const cur=sel.value;const arr=Array.isArray(caps)?caps:[];sel.innerHTML=`<option value="">— Selecciona —</option>`+arr.map(c=>{const pk=c.has_pmkid||/\.(22000|16800)$/i.test(c.filename||'');const tag=pk?' ⚡PMKID':(c.has_handshake?' ✓HS':'');return `<option value="${c.filepath}" data-pmkid="${pk?1:0}" data-essid="${(c.target_essid||'').replace(/"/g,'&quot;')}" ${c.filepath===cur?'selected':''}>${c.filename}${c.target_essid?' ('+c.target_essid+')':''}${tag}</option>`;}).join('')+`<option value="__custom" ${cur==='__custom'?'selected':''}>Ruta personalizada…</option>`;toast('Recargado','success');}catch(e){toast(e.message,'error');}}
async function startHS(){
  const iface=document.getElementById('hs-if')?.value,bssid=document.getElementById('hs-bssid')?.value?.trim(),essid=document.getElementById('hs-essid')?.value?.trim(),ch=parseInt(document.getElementById('hs-ch')?.value)||6,to=parseInt(document.getElementById('hs-to')?.value)||120,da=document.getElementById('hs-da')?.checked,dp=parseInt(document.getElementById('hs-dp')?.value)||10;
  if(!bssid){toast('BSSID obligatorio','warn');return;}
  const btn=document.getElementById('hs-btn');if(btn)btn.disabled=true;
  const empty=document.getElementById('hs-res-empty'),res=document.getElementById('hs-res'),cdown=document.getElementById('hs-cdown');
  if(empty)empty.style.display='none';if(res)res.style.display='none';
  if(cdown){cdown.style.display='block';let rem=to;if(_hsTimer)clearInterval(_hsTimer);_hsTimer=setInterval(()=>{rem--;const cl=rem<10?'low':rem<30?'':'';cdown.innerHTML=`<div style="margin-bottom:12px"><div style="font-size:.72rem;color:var(--t2);text-align:center;margin-bottom:4px">Capturando — <strong>${bssid}</strong></div><div class="cdown ${cl}">${String(Math.floor(rem/60)).padStart(2,'0')}:${String(rem%60).padStart(2,'0')}</div><div style="font-size:.66rem;color:var(--t2);text-align:center;margin-top:2px">segundos restantes</div><div class="ptrack" style="margin-top:8px"><div class="pbar" style="width:${Math.round((1-rem/to)*100)}%"></div></div></div>`;if(rem<=0)clearInterval(_hsTimer);},1000);cdown.innerHTML=`<div class="cdown">${String(Math.floor(to/60)).padStart(2,'0')}:${String(to%60).padStart(2,'0')}</div>`;}
  try{const r=await A.captureHS({interface:iface,target_bssid:bssid,target_essid:essid||null,channel:ch,timeout:to,deauth_first:da,deauth_packets:dp,band:'bg',session_id:ST.activeSession?.id||undefined});
  clearInterval(_hsTimer);if(cdown)cdown.style.display='none';
  if(res){res.style.display='block';res.innerHTML=`<div class="${r.handshake_captured?'alert as':'alert aw'}" style="margin-bottom:12px">${r.handshake_captured?ic('check'):ic('x')}<div><strong>${r.handshake_captured?'¡Handshake capturado!':'Sin handshake'}</strong></div></div>${r.capture_file?`<div style="margin-bottom:8px;font-size:.76rem"><span style="color:var(--t2)">Archivo:</span> <span class="mono" style="color:var(--g)">${r.capture_file}</span></div>`:''}<div style="font-size:.75rem;color:var(--t2)">Duración: ${r.duration_seconds}s · Deauth: ${r.deauth_sent?'Sí':'No'}</div>${r.handshake_captured?`<button class="btn btn-gh btn-sm" style="margin-top:10px" onclick="setIP({'cr-file':'${r.capture_file}','cr-bssid':'${bssid}'});goto('crack')">${ic('zap',12)} Ir a Crack →</button>`:''}`;}  toast(r.handshake_captured?'¡Handshake!':'Sin handshake',r.handshake_captured?'success':'warn');}
  catch(e){clearInterval(_hsTimer);if(cdown)cdown.style.display='none';toast(e.message,'error');if(res){res.style.display='block';res.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}}
  if(btn)btn.disabled=false;}
async function startCrack(){
  const sel=document.getElementById('cr-file');let file=sel?.value;
  if(file==='__custom')file=document.getElementById('cr-cust-file')?.value?.trim();
  const bssid=document.getElementById('cr-bssid')?.value?.trim();
  const essid=document.getElementById('cr-essid')?.value?.trim();
  const wl=document.getElementById('cr-wl')?.value,cust=document.getElementById('cr-cust')?.value?.trim();
  let typ=document.getElementById('cr-type')?.value||'auto';
  if(!file||!bssid){toast('Archivo y BSSID obligatorios','warn');return;}
  if(typ==='auto'){const opt=sel&&sel.options[sel.selectedIndex];const pk=(opt&&opt.getAttribute&&opt.getAttribute('data-pmkid')==='1')||/\.(22000|16800)$/i.test(file);typ=pk?'pmkid':'handshake';}
  const btn=document.getElementById('cr-btn');if(btn)btn.disabled=true;
  const el=document.getElementById('cr-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:8px;color:var(--y)"><div class="spin"></div> Crackeando ${typ==='pmkid'?'PMKID':'handshake'}...</div><div class="ptrack" style="margin-top:10px"><div class="pbar ind"></div></div>`;
  try{
    let r;
    if(typ==='pmkid'){r=await A.pmkidCrack({pmkid_file:file,target_bssid:bssid,target_essid:essid||null,wordlist:wl==='__custom'?'rockyou.txt':wl});}
    else{r=await A.crack({capture_file:file,target_bssid:bssid,wordlist:wl==='__custom'?null:wl,custom_wordlist_path:wl==='__custom'?cust:null});}
    if(el)el.innerHTML=`<div class="${r.success?'alert as':'alert aw'}" style="margin-bottom:12px">${r.success?ic('check'):ic('x')}<div><strong>${r.success?'¡Contraseña encontrada!':'Sin resultado'}</strong> <span class="badge b-c" style="margin-left:4px">${typ==='pmkid'?'PMKID':'HANDSHAKE'}</span></div></div>${r.success?`<div style="padding:14px;background:var(--bg0);border-radius:8px;border:1px solid var(--g);text-align:center;margin-bottom:12px"><div style="font-size:.62rem;color:var(--t2);margin-bottom:4px;letter-spacing:.1em">PASSPHRASE</div><div style="font-family:'Orbitron',monospace;font-size:1.2rem;color:var(--g);word-break:break-all">${r.key}</div></div>`:''}<div style="font-size:.74rem;color:var(--t2)">${r.duration_seconds!=null?'Duración: '+r.duration_seconds+'s':''}${r.keys_tried!=null?' · Claves: '+(r.keys_tried||0).toLocaleString():''}</div>`;
    toast(r.success?`Pass: ${r.key}`:'Sin resultado',r.success?'success':'info');
  }catch(e){toast(e.message,'error');if(el)el.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}
  if(btn)btn.disabled=false;}
async function sendDeauth(){const iface=document.getElementById('da-if')?.value,bssid=(document.getElementById('da-bssid')?.value||document.getElementById('hs-bssid')?.value||'').trim(),cli=document.getElementById('da-cli')?.value?.trim(),pkts=parseInt(document.getElementById('da-pkts')?.value)||50;if(!bssid){toast('BSSID obligatorio','warn');return;}try{const r=await A.deauth({interface:iface,target_bssid:bssid,client_mac:cli||null,packets:pkts,reason:'Manual deauth'});toast(`Deauth: ${r.packets_sent} paquetes → ${r.target}`,'success');}catch(e){toast(e.message,'error');}}
// ======== ADVANCED ========
async function advanced(){
  let ifaces=[],wls=[],caps=[];try{[ifaces,wls,caps]=await Promise.all([A.ifaces(),A.wls(),A.caps()]);}catch{}
  const wlArr=wls?.wordlists||[],capArr=Array.isArray(caps)?caps:[];
  setC(`<div class="sup"><div class="tabs" id="adv-tabs"><div class="tab active" onclick="swTab('adv-tabs','adv-tc',0)">PMKID</div><div class="tab" onclick="swTab('adv-tabs','adv-tc',1)">AP-Less</div><div class="tab" onclick="swTab('adv-tabs','adv-tc',2)">Enterprise</div><div class="tab" onclick="swTab('adv-tabs','adv-tc',3)">WPA3</div></div>
  <div class="tc active" id="adv-tc-0">${pmkT(ifaces,wlArr)}</div>
  <div class="tc" id="adv-tc-1">${aplT(ifaces,wlArr,capArr)}</div>
  <div class="tc" id="adv-tc-2">${entT(ifaces)}</div>
  <div class="tc" id="adv-tc-3">${w3T(ifaces)}</div></div>`);
  pollAplSt();pollEntSt();}
function pmkT(ifaces,wls){return `<div class="g2"><div class="card"><div class="ctitle">${ic('key')} Captura PMKID</div><div class="alert ai" style="margin-bottom:10px">${ic('info')}<div>No requiere cliente conectado.</div></div><div class="frow"><label>Interfaz</label><select id="pmk-if" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name} (${i.mode})</option>`).join('')}</select></div><div class="frow"><label>BSSID *</label><input id="pmk-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="fgrid"><div class="frow"><label>Canal</label><input id="pmk-ch" class="inp" type="number" value="6"></div><div class="frow"><label>Timeout</label><input id="pmk-to" class="inp" type="number" value="60"></div></div><button class="btn btn-g" style="width:100%" id="pmk-btn" onclick="doPmk()">Capturar PMKID</button><div id="pmk-res" style="margin-top:10px"></div></div><div class="card"><div class="ctitle">${ic('zap')} Crack PMKID</div><div class="frow"><label>Archivo PMKID</label><input id="pmkc-f" class="inp" placeholder="/data/pmkid/red.22000"></div><div class="frow"><label>BSSID</label><input id="pmkc-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="frow"><label>ESSID</label><input id="pmkc-essid" class="inp"></div><div class="frow"><label>Wordlist</label><select id="pmkc-wl" class="inp"><option value="rockyou.txt">rockyou.txt</option>${wls.map(w=>`<option value="${w.filename}">${w.filename}</option>`).join('')}</select></div><button class="btn btn-g" style="width:100%" onclick="doPmkCrack()">Crack PMKID</button><div id="pmkc-res" style="margin-top:10px"></div></div></div>`;}
function aplT(ifaces,wls,caps){return `<div class="g2" style="margin-bottom:14px"><div class="card"><div class="ctitle">${ic('wifi')} AP-Less Honeypot</div><div class="alert aw">${ic('warn')}<div>Requiere 2 adaptadores. Crea un AP falso para capturar handshakes.</div></div>
    <div style="padding:11px 13px;background:var(--y2);border:1px solid var(--y);border-left:3px solid var(--y);border-radius:var(--r);margin-bottom:12px;display:flex;gap:9px;align-items:flex-start">
      <span style="font-size:1rem;flex-shrink:0">💡</span>
      <div style="font-size:.76rem;color:var(--y);line-height:1.6">
        <div style="font-weight:700;margin-bottom:3px">Recomendado: clona la MAC de tu interfaz AP con el BSSID objetivo</div>
        <div style="color:var(--t1)">Ve a <b onclick="goto('interfaces')" style="color:var(--c);cursor:pointer;text-decoration:underline">Interfaces</b> → elige tu adaptador AP → <b>Spoof MAC</b> → introduce el BSSID del AP real como MAC personalizada. Así los clientes creen que se conectan al AP legítimo, aumentando mucho la tasa de éxito del honeypot.</div>
      </div>
    </div>
    <div class="frow"><label>Iface Monitor</label><select id="apl-mon" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="frow"><label>Iface AP</label><select id="apl-ap" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="fgrid"><div class="frow"><label>ESSID AP falso</label><input id="apl-essid" class="inp" placeholder="FreeWiFi"></div><div class="frow"><label>Canal</label><input id="apl-ch" class="inp" type="number" value="6"></div></div><div class="fgrid"><div class="frow"><label>WPA</label><select id="apl-wpa" class="inp"><option value="2">WPA2</option><option value="1">WPA</option></select></div><div class="frow"><label>Pass falsa</label><input id="apl-pass" class="inp" value="fakepass123"></div></div><div style="display:flex;gap:7px"><button class="btn btn-g" style="flex:1" onclick="doAplStart()">Iniciar</button><button class="btn btn-d" style="flex:1" onclick="doAplStop()">Detener</button></div></div><div class="card"><div class="ctitle">${ic('refresh')} Estado + Deauth</div><div id="apl-st" class="empty" style="padding:18px">${ic('wifi',30)}<h3>Inactivo</h3></div><div style="border:1px solid var(--b0);border-radius:8px;padding:11px;margin-top:11px;background:var(--bg3)"><div style="font-size:.66rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px">Deauth al AP legítimo</div><div class="frow"><label>BSSID AP legítimo</label><input id="apl-da-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="fgrid"><div class="frow"><label>Interfaz</label><select id="apl-da-if" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="frow"><label>Paquetes</label><input id="apl-da-pkts" class="inp" type="number" value="50"></div></div><button class="btn btn-d btn-sm" style="width:100%" onclick="doAplDA()">Enviar Deauth</button></div></div></div><div class="g2"><div class="card"><div class="ctitle">${ic('key')} Handshake Capturado</div><div id="apl-hs-st" class="empty" style="padding:18px">${ic('key',30)}<h3>Sin handshake</h3></div></div><div class="card"><div class="ctitle">${ic('zap')} Crack AP-Less</div><div class="frow"><label>Archivo</label><select id="apl-cr-f" class="inp"><option value="">— Selecciona —</option>${caps.map(c=>`<option value="${c.filepath}">${c.filename}${c.has_handshake?' ✓HS':''}</option>`).join('')}</select></div><div class="frow"><label>BSSID</label><input id="apl-cr-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="frow"><label>Wordlist</label><select id="apl-cr-wl" class="inp"><option value="rockyou.txt">rockyou.txt</option>${wls.map(w=>`<option value="${w.filename}">${w.filename}</option>`).join('')}</select></div><button class="btn btn-g" style="width:100%" onclick="doAplCrack()">Crack</button><div id="apl-cr-res" style="margin-top:10px"></div></div></div>`;}
function entT(ifaces){return `<div class="g2"><div class="card"><div class="ctitle">${ic('shield')} Rogue RADIUS</div><div class="alert aw">${ic('warn')}<div>Captura credenciales EAP. Requiere 2 adaptadores.</div></div><div class="frow"><label>Iface Monitor</label><select id="ent-mon" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="frow"><label>Iface AP</label><select id="ent-ap" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="fgrid"><div class="frow"><label>ESSID objetivo</label><input id="ent-essid" class="inp" placeholder="Corp-WiFi"></div><div class="frow"><label>Canal</label><input id="ent-ch" class="inp" type="number" value="6"></div></div><div class="frow"><label>EAP</label><select id="ent-eap" class="inp"><option value="PEAP">PEAP</option><option value="TTLS">TTLS</option><option value="FAST">FAST</option></select></div><div style="display:flex;gap:7px;margin-top:8px"><button class="btn btn-g" style="flex:1" onclick="doEntStart()">Iniciar</button><button class="btn btn-d" style="flex:1" onclick="doEntStop()">Detener</button></div></div><div class="card"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px"><div class="ctitle" style="margin-bottom:0">${ic('key')} Estado + Credenciales</div><button class="btn btn-gh btn-xs" onclick="pollEntSt()">${ic('refresh',11)} Actualizar</button></div><div id="ent-st"></div><div id="ent-creds" class="empty" style="padding:20px">${ic('key',30)}<h3>Sin credenciales</h3><p>Se muestran aquí cuando una víctima intenta autenticarse</p></div></div></div>`;}
function w3T(ifaces){return `<div class="card" style="max-width:500px"><div class="ctitle">${ic('zap')} Ataque WPA3</div><div class="alert ai">${ic('info')}<div>Downgrade, Transition Mode, DoS (Dragonblood).</div></div><div class="frow"><label>Interfaz</label><select id="w3-if" class="inp">${ifaces.map(i=>`<option value="${i.name}">${i.name}</option>`).join('')}</select></div><div class="fgrid"><div class="frow"><label>BSSID</label><input id="w3-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="frow"><label>Canal</label><input id="w3-ch" class="inp" type="number" value="6"></div></div><div class="frow"><label>ESSID</label><input id="w3-essid" class="inp" placeholder="WPA3-Network"></div><div class="frow"><label>Tipo</label><select id="w3-type" class="inp"><option value="downgrade">Downgrade</option><option value="transition_mode">Transition Mode</option><option value="dos">DoS</option></select></div><button class="btn btn-g" style="width:100%;margin-top:8px" onclick="doW3()">Ejecutar</button><div id="w3-res" style="margin-top:10px"></div></div>`;}
async function doPmk(){const i=document.getElementById('pmk-if')?.value,b=document.getElementById('pmk-bssid')?.value?.trim(),c=parseInt(document.getElementById('pmk-ch')?.value)||6,t=parseInt(document.getElementById('pmk-to')?.value)||60;if(!b){toast('BSSID obligatorio','warn');return;}const btn=document.getElementById('pmk-btn');if(btn)btn.disabled=true;const el=document.getElementById('pmk-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:7px;color:var(--y)"><div class="spin"></div> Capturando...</div>`;try{const r=await A.pmkidCap({interface:i,target_bssid:b,channel:c,timeout:t});if(el)el.innerHTML=`<div class="${r.pmkid_captured?'alert as':'alert aw'}">${r.pmkid_captured?ic('check'):ic('x')}<div>${r.pmkid_captured?'¡PMKID! '+r.pmkid_file:'Sin PMKID'}</div></div>`;toast(r.pmkid_captured?'PMKID capturado':'Sin PMKID',r.pmkid_captured?'success':'warn');}catch(e){toast(e.message,'error');if(el)el.innerHTML=`<div class="alert ae">${e.message}</div>`;}if(btn)btn.disabled=false;}
async function doPmkCrack(){const f=document.getElementById('pmkc-f')?.value?.trim(),b=document.getElementById('pmkc-bssid')?.value?.trim(),e2=document.getElementById('pmkc-essid')?.value?.trim(),wl=document.getElementById('pmkc-wl')?.value||'rockyou.txt';if(!f||!b){toast('Archivo y BSSID obligatorios','warn');return;}const el=document.getElementById('pmkc-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:7px;color:var(--y)"><div class="spin"></div> Crackeando...</div>`;try{const r=await A.pmkidCrack({pmkid_file:f,target_bssid:b,target_essid:e2,wordlist:wl});if(el)el.innerHTML=`<div class="${r.success?'alert as':'alert aw'}">${r.success?ic('check'):ic('x')}<div>${r.success?`Contraseña: <strong>${r.key}</strong>`:'Sin resultado'}</div></div>`;toast(r.success?'Pass: '+r.key:'Sin resultado',r.success?'success':'info');}catch(e){toast(e.message,'error');}}
async function doAplStart(){const mon=document.getElementById('apl-mon')?.value,ap=document.getElementById('apl-ap')?.value,essid=document.getElementById('apl-essid')?.value?.trim(),ch=parseInt(document.getElementById('apl-ch')?.value)||6;if(!essid){toast('ESSID obligatorio','warn');return;}try{const r=await A.aplStart({monitor_interface:mon,ap_interface:ap,target_essid:essid,channel:ch,wpa_version:parseInt(document.getElementById('apl-wpa')?.value)||2,fake_passphrase:document.getElementById('apl-pass')?.value||'fake123',capture_timeout:300});toast(r.started?'AP-Less iniciado':'Error',r.started?'success':'error');pollAplSt();}catch(e){toast(e.message,'error');}}
async function doAplStop(){try{await A.aplStop();toast('AP-Less detenido','success');}catch(e){toast(e.message,'error');}}
async function doAplDA(){const i=document.getElementById('apl-da-if')?.value,b=document.getElementById('apl-da-bssid')?.value?.trim(),p=parseInt(document.getElementById('apl-da-pkts')?.value)||50;if(!b){toast('BSSID obligatorio','warn');return;}try{const r=await A.deauth({interface:i,target_bssid:b,client_mac:null,packets:p,reason:'AP-Less deauth'});toast(`Deauth: ${r.packets_sent} paquetes`,'success');}catch(e){toast(e.message,'error');}}
async function doAplCrack(){const f=document.getElementById('apl-cr-f')?.value,b=document.getElementById('apl-cr-bssid')?.value?.trim(),wl=document.getElementById('apl-cr-wl')?.value||'rockyou.txt';if(!f||!b){toast('Archivo y BSSID obligatorios','warn');return;}const el=document.getElementById('apl-cr-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:7px;color:var(--y)"><div class="spin"></div> Crackeando...</div>`;try{const r=await A.crack({capture_file:f,target_bssid:b,wordlist:wl});if(el)el.innerHTML=`<div class="${r.success?'alert as':'alert aw'}">${r.success?ic('check'):ic('x')}<div>${r.success?`Contraseña: <strong>${r.key}</strong>`:'Sin resultado'}</div></div>`;toast(r.success?'Pass: '+r.key:'Sin resultado',r.success?'success':'info');}catch(e){toast(e.message,'error');}}
async function pollAplSt(){try{const st=await A.aplSt();const el=document.getElementById('apl-st');if(!el)return;if(st.active){el.innerHTML=`<div class="alert as">${ic('check')}<div>Activo · ESSID: <strong>${st.target_essid||'—'}</strong></div></div><div style="font-size:.8rem;color:var(--t2);margin-top:6px">Capturas: <strong>${st.captures_count||0}</strong></div>`;const hs=document.getElementById('apl-hs-st');if(hs&&st.handshake_captured){hs.innerHTML=`<div class="alert as">${ic('check')}<div><strong>¡Handshake!</strong><br><span class="mono">${st.capture_file||''}</span></div></div>`;const s=document.getElementById('apl-cr-f');if(s&&st.capture_file){const o=document.createElement('option');o.value=st.capture_file;o.text=st.capture_file.split('/').pop()+' ✓HS';o.selected=true;s.add(o,1);}}}else{el.innerHTML=`<div class="empty" style="padding:16px">${ic('wifi',28)}<h3>Inactivo</h3></div>`;}}catch{}}
async function doEntStart(){const mon=document.getElementById('ent-mon')?.value,ap=document.getElementById('ent-ap')?.value,essid=document.getElementById('ent-essid')?.value?.trim(),ch=parseInt(document.getElementById('ent-ch')?.value)||6,eap=document.getElementById('ent-eap')?.value;if(!essid){toast('ESSID obligatorio','warn');return;}try{const r=await A.entStart({monitor_interface:mon,ap_interface:ap,target_essid:essid,channel:ch,eap_type:eap,capture_creds:true});toast(r.started?'Enterprise iniciado':'Error',r.started?'success':'error');pollEntSt();}catch(e){toast(e.message,'error');}}
async function doEntStop(){try{await A.entStop();toast('Enterprise detenido','success');pollEntSt();}catch(e){toast(e.message,'error');}}
async function pollEntSt(){const st=document.getElementById('ent-st'),cr=document.getElementById('ent-creds');if(!st)return;try{const[s,creds]=await Promise.all([A.entSt().catch(()=>null),A.entCreds().catch(()=>[])]);const arr=Array.isArray(creds)?creds:[];if(s&&s.active){const a=s.attack||{};st.innerHTML=`<div class="alert as" style="margin-bottom:10px">${ic('check')}<div>Activo${a.target_essid?` · ESSID: <strong>${a.target_essid}</strong>`:''}${a.eap_type?` · <span class="badge b-c">${a.eap_type}</span>`:''}</div></div><div style="font-size:.8rem;color:var(--t2);margin-bottom:8px">Credenciales capturadas: <strong style="color:var(--r)">${s.captured_credentials||0}</strong></div>`;}else{st.innerHTML=`<div class="alert ai" style="margin-bottom:8px">${ic('info')}<div>Rogue RADIUS inactivo</div></div>`;}if(cr){if(!arr.length){cr.className='empty';cr.style.padding='20px';cr.innerHTML=`${ic('key',30)}<h3>Sin credenciales</h3><p>Se muestran aquí cuando una víctima intenta autenticarse</p>`;}else{cr.className='';cr.style.padding='0';cr.innerHTML=`<div class="twrap"><table><thead><tr><th>Usuario</th><th>Challenge/Hash</th><th>Tipo</th><th>Hora</th></tr></thead><tbody>${arr.map(c=>`<tr style="background:var(--r2)"><td class="mono" style="font-size:.76rem;color:var(--r)"><strong>${c.username||c.identity||'—'}</strong></td><td class="mono" style="font-size:.66rem;color:var(--t2);max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${c.hash||c.challenge||c.response||''}">${c.hash||c.challenge||c.response||'—'}</td><td><span class="badge b-o">${c.eap_type||c.type||'EAP'}</span></td><td class="mono" style="font-size:.66rem;color:var(--t2)">${c.timestamp?fd(c.timestamp):'—'}</td></tr>`).join('')}</tbody></table></div><div style="font-size:.68rem;color:var(--t2);margin-top:8px">${ic('info',10)} Crackea los hashes MSCHAPv2 con <span class="hcode" style="font-size:.66rem">hashcat -m 5500</span></div>`;}}}catch(e){}}
async function doW3(){const i=document.getElementById('w3-if')?.value,b=document.getElementById('w3-bssid')?.value?.trim(),e2=document.getElementById('w3-essid')?.value?.trim(),c=parseInt(document.getElementById('w3-ch')?.value)||6,t=document.getElementById('w3-type')?.value;if(!b){toast('BSSID obligatorio','warn');return;}const el=document.getElementById('w3-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:7px;color:var(--y)"><div class="spin"></div> Ejecutando...</div>`;try{const r=await A.wpa3({interface:i,target_bssid:b,target_essid:e2,channel:c,attack_type:t,timeout:120});if(el)el.innerHTML=`<div class="${r.success?'alert as':'alert aw'}">${r.success?ic('check'):ic('x')}<div>${t} · ${r.success?'Exitoso':'Sin resultado'}</div></div>`;toast(r.success?'OK':'Sin resultado',r.success?'success':'info');}catch(e){toast(e.message,'error');if(el)el.innerHTML=`<div class="alert ae">${e.message}</div>`;}}
