// WFAudit · recopilación — dashboard, interfaces, escaneo WiFi y reconocimiento (nmap)
// ======== DASHBOARD ========
async function dashboard(){
  setC(`<div style="display:flex;align-items:center;gap:10px;color:var(--t2)"><div class="spin"></div> Cargando...</div>`);
  let pf=null,procs=[],sess=[];
  try{[pf,procs,sess]=await Promise.all([A.preflight().catch(()=>null),A.procs().catch(()=>[]),A.sessions().catch(()=>[])]);}catch{}
  const sys=pf?.system||{},tools=pf?.tools||{},tl=Object.entries(tools),inst=tl.filter(([,v])=>v.installed).length,miss=pf?.missing_critical||[],run=procs.filter(p=>p.status==='running'),s=ST.activeSession,fi=s?.findings||[],sc={critical:0,high:0,medium:0,low:0,info:0};
  fi.forEach(f=>{if(f.severity in sc)sc[f.severity]++;});
  setC(`<div class="sup">
    ${miss.length?`<div class="alert aw" style="margin-bottom:14px">${ic('warn')}<div><strong>Críticos faltantes:</strong> ${miss.join(', ')} — <span onclick="goto('system')" style="cursor:pointer;text-decoration:underline">Ver sistema</span></div></div>`:''}
    <div class="g4" style="margin-bottom:14px">
      <div class="card ${pf?.ready?'card-g':''}">
        <div class="ctitle">${ic('cpu')} Sistema</div>
        <div style="font-family:'Orbitron',monospace;font-size:.95rem;font-weight:700;color:var(--g)">${sys.hostname||'—'}</div>
        <div style="font-size:.7rem;color:var(--t2);margin:4px 0 8px">${sys.os||'—'}</div>
        <div style="display:flex;gap:5px;flex-wrap:wrap">${sys.is_root?`<span class="badge b-g">ROOT ✓</span>`:`<span class="badge b-r">NO ROOT</span>`}${sys.cpu_count?`<span class="badge b-x">${sys.cpu_count} cores</span>`:''}</div>
      </div>
      <div class="card">
        <div class="ctitle">${ic('zap')} Herramientas</div>
        <div style="font-family:'Orbitron',monospace;font-size:1.5rem;font-weight:700">${inst}<span style="font-size:.85rem;color:var(--t2)">/${tl.length}</span></div>
        <div class="ptrack" style="margin:8px 0 5px"><div class="pbar" style="width:${tl.length?Math.round(inst/tl.length*100):0}%"></div></div>
        <div style="font-size:.7rem;color:${miss.length?'var(--r)':'var(--g)'}">${miss.length?`${miss.length} críticos faltantes`:'Todas OK'}</div>
      </div>
      <div class="card">
        <div class="ctitle">${ic('folder')} Sesiones</div>
        <div style="font-family:'Orbitron',monospace;font-size:1.5rem;font-weight:700">${sess.length}</div>
        <div style="font-size:.7rem;color:var(--t2);margin-top:4px">${sess.filter(x=>x.status==='active').length} activas</div>
        <button class="btn btn-gh btn-xs" style="margin-top:8px" onclick="goto('sessions')">Gestionar →</button>
      </div>
      <div class="card">
        <div class="ctitle">${ic('refresh')} Procesos</div>
        <div style="font-family:'Orbitron',monospace;font-size:1.5rem;font-weight:700;color:${run.length?'var(--y)':'var(--t0)'}" class="${run.length?'ppulse':''}">${run.length}</div>
        <div style="font-size:.7rem;color:var(--t2);margin-top:4px">${procs.length} total</div>
        <button class="btn btn-gh btn-xs" style="margin-top:8px" onclick="goto('system')">Ver →</button>
      </div>
    </div>
    <div class="g2" style="margin-bottom:14px">
      <div class="card ${s?'card-c glow-c':''}">
        <div class="ctitle">${ic('folder')} Sesión Activa</div>
        ${s?`<div style="font-family:'Orbitron',monospace;font-size:.95rem;font-weight:700;margin-bottom:4px">${s.name}</div>
          <div style="font-size:.74rem;color:var(--t2);margin-bottom:8px">${s.company||'—'} · ${s.auditor||'—'} · <span class="mono">${s.id}</span></div>
          ${stb(s.status)}
          ${fi.length>0?`<div style="margin:10px 0 6px"><div style="display:flex;height:6px;border-radius:3px;overflow:hidden;margin-bottom:7px">${Object.entries(sc).filter(([,v])=>v>0).map(([sv,n])=>`<div style="flex:${n};background:var(--${sv==='critical'?'r':sv==='high'?'o':sv==='medium'?'y':sv==='low'?'g':'c'})" title="${sv}:${n}"></div>`).join('')}</div><div style="display:flex;gap:5px;flex-wrap:wrap">${Object.entries(sc).filter(([,v])=>v>0).map(([sv,n])=>`<span class="badge b-${sv==='critical'?'r':sv==='high'?'o':sv==='medium'?'y':sv==='low'?'g':'c'}">${sv}:${n}</span>`).join('')}</div></div>`:`<div style="font-size:.76rem;color:var(--t2);margin-top:8px">Sin hallazgos</div>`}
          <div style="display:flex;gap:7px;margin-top:12px;flex-wrap:wrap"><button class="btn btn-gh btn-sm" onclick="goto('sessions')">Ver sesión</button><button class="btn btn-p btn-sm" onclick="addFindingModal('${s.id}')">${ic('plus')} Hallazgo</button><a class="btn btn-gh btn-sm" href="${A.pdfUrl(s.id)}" target="_blank">${ic('download')} PDF</a></div>`:
        `<div class="empty" style="padding:22px">${ic('folder',36)}<h3>Sin sesión activa</h3><button class="btn btn-g btn-sm" style="margin-top:10px" onclick="goto('sessions')">${ic('plus')} Nueva</button></div>`}
      </div>
      <div class="card">
        <div class="ctitle">${ic('zap')} Accesos Rápidos</div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
          ${[['wifi','Escanear WiFi','wifiscan','var(--c)'],['search','Reconocimiento','recon','var(--g)'],['wifi','Sniffing','sniffing','var(--y)'],['key','Crack','crack','var(--y)'],['shield','Evil Twin','attacks','var(--o)'],['zap','Avanzado','advanced','var(--p)'],['download','Wordlists','wordlists','var(--c)']].map(([i2,l,s2,col])=>`<div onclick="goto('${s2}')" style="padding:12px;background:var(--bg3);border:1px solid var(--b0);border-radius:9px;cursor:pointer;transition:all .15s" onmouseover="this.style.borderColor='${col}'" onmouseout="this.style.borderColor='var(--b0)'"><div style="color:${col}">${ic(i2,16)}</div><div style="font-size:.8rem;font-weight:600;margin-top:5px">${l}</div></div>`).join('')}
        </div>
      </div>
    </div>
    <div class="card">
      <div style="display:flex;justify-content:space-between;margin-bottom:10px"><div class="ctitle" style="margin-bottom:0">${ic('zap')} Herramientas</div><button class="btn btn-gh btn-xs" onclick="goto('system')">Ver todo →</button></div>
      <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(148px,1fr));gap:6px">
        ${tl.slice(0,16).map(([name,t])=>`<div style="display:flex;align-items:center;gap:7px;padding:7px;background:var(--bg3);border-radius:6px;border:1px solid ${t.installed?'rgba(0,255,136,.2)':'rgba(255,59,92,.15)'}"><div style="width:6px;height:6px;border-radius:50%;background:${t.installed?'var(--g)':'var(--r)'};flex-shrink:0"></div><span class="mono" style="font-size:.72rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1">${name}</span></div>`).join('')}
      </div>
    </div>
    ${run.length?`<div class="card" style="margin-top:14px"><div class="ctitle">${ic('refresh')} Procesos Activos</div><div class="twrap"><table><thead><tr><th>ID</th><th>Comando</th><th>Estado</th><th>Inicio</th><th></th></tr></thead><tbody>${run.map(p=>`<tr><td class="mono" style="font-size:.7rem">${p.id}</td><td class="mono" style="max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.68rem;color:var(--t2)">${p.command}</td><td>${stb(p.status)}</td><td class="mono" style="font-size:.68rem;color:var(--t2)">${fd(p.started_at)}</td><td><button class="btn btn-d btn-xs" onclick="cancelPD('${p.id}')">Stop</button></td></tr>`).join('')}</tbody></table></div></div>`:''}
  </div>`);}
async function cancelPD(id){try{await A.cancelProc(id);toast('Cancelado','success');dashboard();}catch(e){toast(e.message,'error');}}
// ======== SESSIONS ========
async function interfaces(){
  setC(`<div style="display:flex;align-items:center;gap:10px;color:var(--t2)"><div class="spin"></div> Cargando...</div>`);
  let ifaces=[],ns=null;try{[ifaces,ns]=await Promise.all([A.ifaces(),A.netSt()]);}catch(e){toast(e.message,'error');}
  const sug=(ns?.suggestions||[]).filter(s=>s.level!=='ok'),mon=ifaces.filter(i=>i.mode==='monitor'),mgd=ifaces.filter(i=>i.mode==='managed'&&i.is_up),down=ifaces.filter(i=>!i.is_up);
  setC(`<div class="sup">
    <div class="hint" style="margin-bottom:10px">${ic('info',12)}<b>Monitor</b> = captura todas las tramas del aire (necesario para escanear, capturar handshakes y deauth). <b>Managed</b> = cliente normal (para conectarte a una red o hacer MITM/recon). Pasa a monitor la interfaz con la que vayas a auditar; recuerda volver a managed al terminar.</div>
    ${sug.map(s=>`<div class="alert ${s.level==='warning'?'aw':'ai'}" style="margin-bottom:8px">${ic(s.level==='warning'?'warn':'info')}<div>${s.message}</div></div>`).join('')}
    ${ns?`<div style="background:var(--bg1);border:1px solid var(--b0);border-radius:var(--rl);padding:14px;margin-bottom:18px">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:12px"><div class="ctitle" style="margin-bottom:0">${ic('wifi')} Estado de Red</div><span class="badge ${ns.internet_available?'b-g':'b-r'}" style="margin-left:auto">${ns.internet_available?'Internet OK':'Sin Internet'}</span></div>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px">
        ${[['Ethernet',ns.ethernet||[],'var(--c)'],['WiFi Managed',ns.wifi_managed||[],'var(--g)'],['WiFi Monitor',ns.wifi_monitor||[],'var(--y)']].map(([lbl,items,col])=>`<div><div class="net-col">${lbl}</div>${items.length?items.map(i=>`<div class="net-e"><div style="width:7px;height:7px;border-radius:50%;background:${i.state==='up'?col:'var(--t2)'};flex-shrink:0;${i.state==='up'?`box-shadow:0 0 5px ${col};`:''}"></div><span class="mono" style="font-size:.75rem">${i.interface}</span>${i.ipv4?`<span style="font-size:.72rem;color:var(--t2)">${i.ipv4}</span>`:''}<span class="badge ${i.state==='up'?'b-g':'b-x'}" style="margin-left:auto">${i.state}</span></div>`).join(''):`<div style="font-size:.74rem;color:var(--t2);padding:4px 0">—</div>`}</div>`).join('')}
      </div>
    </div>`:''}
    ${mon.length?`<div class="iface-sec">${ic('wifi',12)} MONITOR MODE (${mon.length})</div><div style="display:flex;flex-direction:column;gap:12px;margin-bottom:16px">${mon.map(ifCard).join('')}</div>`:''}
    ${mgd.length?`<div class="iface-sec">${ic('wifi',12)} MANAGED MODE (${mgd.length})</div><div style="display:flex;flex-direction:column;gap:12px;margin-bottom:16px">${mgd.map(ifCard).join('')}</div>`:''}
    ${down.length?`<div class="iface-sec">DOWN (${down.length})</div><div style="display:flex;flex-direction:column;gap:10px">${down.map(ifCard).join('')}</div>`:''}
    ${!ifaces.length?`<div class="empty">${ic('wifi',48)}<h3>Sin interfaces WiFi</h3></div>`:''}
  </div>`);}
function ifCard(i){const cl=!i.is_up?'iface-down':i.mode==='monitor'?'iface-mon':'iface-mgd';return `<div class="${cl}"><div class="iface-name">${i.name}</div><div class="iface-meta"><span>MAC: <strong class="mono">${i.mac||'—'}</strong></span><span>Driver: <strong>${i.driver||'—'}</strong></span><span>Chipset: <strong>${i.chipset||'—'}</strong></span><span>TX: <strong>${i.tx_power||'?'} dBm</strong></span>${i.phy?`<span>PHY: <strong>${i.phy}</strong></span>`:''}</div><div style="display:flex;gap:6px;margin-bottom:12px;flex-wrap:wrap">${i.supports_monitor?`<span class="badge b-g">Monitor ✓</span>`:''} ${i.supports_5ghz?`<span class="badge b-c">5GHz ✓</span>`:''} ${i.supports_inject?`<span class="badge b-p">Inject ✓</span>`:''}</div><div style="display:flex;gap:7px;flex-wrap:wrap">${i.mode==='managed'?`<button class="btn btn-g btn-sm" onclick="setMon('${i.name}')">→ Monitor</button>`:`<button class="btn btn-gh btn-sm" onclick="setMgd('${i.name}')">→ Managed</button>`}<button class="btn btn-gh btn-sm" onclick="spoofUI('${i.name}')">Spoof MAC</button><button class="btn btn-gh btn-sm" onclick="txUI('${i.name}',${i.tx_power||20})">TX Power</button><button class="btn btn-gh btn-sm" onclick="showChannels('${i.name}')">Canales</button></div></div>`;}
async function showChannels(n){showModal(`Canales soportados — ${n}`,`<div style="display:flex;align-items:center;gap:8px;color:var(--y)"><div class="spin"></div> Consultando...</div>`,'',false);try{const r=await A.channels(n);const arr=Array.isArray(r)?r:(r.channels||r.supported_channels||[]);const g24=arr.filter(c=>c<=14),g5=arr.filter(c=>c>14);const chip=c=>`<span class="kbd" style="margin:2px">${c}</span>`;showModal(`Canales soportados — ${n}`,`${!arr.length?`<div class="alert ai">${ic('info')}<div>Sin datos de canales para esta interfaz.</div></div>`:`<div style="font-size:.72rem;color:var(--t2);margin-bottom:10px">${arr.length} canales soportados</div>${g24.length?`<div style="font-size:.66rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px">2.4 GHz</div><div style="margin-bottom:12px;line-height:2">${g24.map(chip).join('')}</div>`:''}${g5.length?`<div style="font-size:.66rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px">5 GHz</div><div style="line-height:2">${g5.map(chip).join('')}</div>`:''}`}`,`<button class="btn btn-gh" onclick="closeModal()">Cerrar</button>`,false);}catch(e){toast(e.message,'error');closeModal();}}
async function setMon(n){try{const r=await A.setMon(n);toast(r.success?`${n} → monitor (${r.monitor_interface})`:'Error',r.success?'success':'error');interfaces();}catch(e){toast(e.message,'error');}}
async function setMgd(n){try{await A.setMgd(n);toast(`${n} → managed`,'success');interfaces();}catch(e){toast(e.message,'error');}}
function spoofUI(n){showModal(`Spoof MAC — ${n}`,`<div class="alert aw">${ic('warn')}<div>Puede interrumpir la conexión.</div></div><div class="frow"><label>Nueva MAC (vacío=aleatoria)</label><input id="sm-mac" class="inp" placeholder="AA:BB:CC:DD:EE:FF"></div><div class="frow"><label>Vendor prefix (opcional) <span class="tip" data-tip="Clona solo los 3 primeros octetos para imitar a un fabricante (ej. 00:1A:2B). El resto es aleatorio. Ignorado si rellenas una MAC completa arriba.">?</span></label><input id="sm-vp" class="inp" placeholder="00:1A:2B (Cisco, Apple…)"></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-p" onclick="doSpoof('${n}')">Aplicar</button>`);}
async function doSpoof(n){const m=document.getElementById('sm-mac')?.value?.trim(),vp=document.getElementById('sm-vp')?.value?.trim();try{const r=await A.spoofMac(n,m||null,vp||null);closeModal();toast(`Nueva MAC: ${r.new_mac}`,'success');interfaces();}catch(e){toast(e.message,'error');}}
function txUI(n,c){showModal(`TX Power — ${n}`,`<div class="frow"><label>Potencia dBm (1–30)</label><input id="tx-v" class="inp" type="number" min="1" max="30" value="${c}"></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-p" onclick="doTx('${n}')">Aplicar</button>`);}
async function doTx(n){const p=parseInt(document.getElementById('tx-v')?.value);try{const r=await A.setTx(n,p);closeModal();toast(`TX → ${r.tx_power} dBm`,'success');interfaces();}catch(e){toast(e.message,'error');}}
// ======== WIFI SCAN ========
let _scan=null,_scanPoll=null;
async function wifiscan(){
  let ifaces=[];try{ifaces=await A.ifaces();}catch{}
  setC(`<div class="sup"><div class="g2" style="margin-bottom:16px"><div class="card" id="ws-form" data-pp="ws-form">
    <div class="ctitle">${ic('search')} Nueva Exploración</div>
    ${!ifaces.filter(i=>i.mode==='monitor').length?`<div class="alert aw" style="margin-bottom:10px">${ic('warn')}<div>Sin interfaces en monitor. <button class="btn btn-gh btn-xs" onclick="goto('interfaces')">Ir a Interfaces →</button></div></div>`:''}
    <div class="fgrid">
      <div class="frow"><label>Interfaz</label><select id="ws-if" class="inp" data-p>${ifaces.map(i=>`<option value="${i.name}" ${i.mode==='monitor'?'selected':''}>${i.name} (${i.mode})</option>`).join('')}</select></div>
      <div class="frow"><label>Banda <span class="tip" data-tip="2.4 GHz: routers domésticos e IoT (rápido). 5 GHz: redes corporativas modernas. Dual Band: ambas a la vez (recomendado, no pierdes redes).">?</span></label><select id="ws-band" class="inp" data-p><option value="bg">2.4 GHz (b/g/n)</option><option value="a">5 GHz (a/n/ac)</option><option value="abg">Dual Band</option></select></div>
      <div class="frow"><label>Duración (seg) <span class="tip" data-tip="30s: reconocimiento rápido. 60-120s: equilibrado (recomendado). 300s+: captura redes ocultas, clientes poco activos y señales débiles.">?</span></label><input id="ws-dur" class="inp" type="number" value="30" min="10" max="300" data-p></div>
      <div class="frow"><label>Canal (opcional)</label><input id="ws-ch" class="inp" type="number" placeholder="Todos" data-p></div>
    </div>
    <div class="fgrid">
      <div class="frow"><label>BSSID objetivo <span class="tip" data-tip="Opcional. Filtra el escaneo a un único AP por su MAC. Reduce ruido y consumo cuando ya sabes qué red quieres.">?</span></label><input id="ws-bssid" class="inp" placeholder="AA:BB:CC:DD:EE:FF" data-p></div>
      <div class="frow"><label>ESSID objetivo <span class="tip" data-tip="Opcional. Filtra el escaneo a las redes con este nombre. Déjalo vacío para ver todas.">?</span></label><input id="ws-essid" class="inp" placeholder="Nombre de red" data-p></div>
    </div>
    <button class="btn btn-g" style="width:100%" id="ws-btn" onclick="startScan()">${ic('play')} Iniciar Escaneo</button>
  </div>
  <div class="card" id="ws-status-card">
    <div class="ctitle">${ic('refresh')} Estado</div>
    <div id="ws-empty" class="empty" style="padding:22px">${ic('search',36)}<h3>Sin escaneo activo</h3></div>
    <div id="ws-live" style="display:none"></div>
  </div></div>
  <div id="ws-results"></div>
  <div id="ws-history"><div style="font-family:'Orbitron',monospace;font-size:.68rem;color:var(--t2);letter-spacing:.1em;text-transform:uppercase;margin-bottom:9px">${ic('folder',12)} Escaneos Anteriores</div><div id="ws-hist-list"><div style="color:var(--t2);font-size:.78rem">Cargando...</div></div></div>
  </div>`);
  restFP('ws-form');
  if(ST.lastScan)renderScanR(ST.lastScan);
  loadScHist();}
async function loadScHist(){try{const sc=await A.listScans();const el=document.getElementById('ws-hist-list');if(!el)return;if(!sc.length){el.innerHTML=`<div style="color:var(--t2);font-size:.78rem">Sin escaneos previos</div>`;return;}el.innerHTML=`<div class="twrap"><table><thead><tr><th>ID</th><th>Iface</th><th>Banda</th><th>APs</th><th>Estado</th><th>Inicio</th><th></th></tr></thead><tbody>${sc.slice(0,10).map(s=>`<tr><td class="mono" style="font-size:.7rem">${s.id}</td><td class="mono" style="font-size:.72rem">${s.interface||'—'}</td><td><span class="badge b-c">${s.band||'—'}</span></td><td><strong>${s.access_points?.length||0}</strong></td><td>${stb(s.status)}</td><td class="mono" style="font-size:.68rem;color:var(--t2)">${fd(s.started_at)}</td><td><button class="btn btn-gh btn-xs" onclick="loadScanR('${s.id}')">Ver</button></td></tr>`).join('')}</tbody></table></div>`;}catch{}}
async function startScan(){const iface=document.getElementById('ws-if')?.value,band=document.getElementById('ws-band')?.value||'bg',dur=parseInt(document.getElementById('ws-dur')?.value)||30,ch=document.getElementById('ws-ch')?.value,bssid=document.getElementById('ws-bssid')?.value?.trim(),essid=document.getElementById('ws-essid')?.value?.trim();if(!iface){toast('Selecciona interfaz','warn');return;}try{document.getElementById('ws-btn').disabled=true;const sc=await A.startScan({interface:iface,band,duration:dur,channel:ch?parseInt(ch):null,target_bssid:bssid||null,target_essid:essid||null});_scan=sc;toast('Escaneo iniciado','success');startScanPoll(sc.id,dur);}catch(e){toast(e.message,'error');const b=document.getElementById('ws-btn');if(b)b.disabled=false;}}
function startScanPoll(id,dur){let el=0;if(_scanPoll)clearInterval(_scanPoll);updateScanSt(null,0,dur,'running');_scanPoll=setInterval(async()=>{el=Math.min(el+2,dur);try{const sc=await A.getScan(id);_scan=sc;updateScanSt(sc,el,dur,sc.status);if(sc.status!=='running'){clearInterval(_scanPoll);_scanPoll=null;ST.lastScan=sc;localStorage.setItem('lastScan',JSON.stringify(sc));renderScanR(sc);loadScHist();const b=document.getElementById('ws-btn');if(b)b.disabled=false;}}catch{}},2000);}
function updateScanSt(sc,el,tot,st){const live=document.getElementById('ws-live'),empty=document.getElementById('ws-empty');if(!live)return;if(empty)empty.style.display='none';live.style.display='block';const p=tot?Math.round(el/tot*100):0;live.innerHTML=`<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;margin-bottom:5px"><span style="font-size:.78rem;color:var(--t1)">${st==='running'?'🔄 Escaneando...':st==='completed'?'✅ Completado':'❌ '+st}</span><span class="mono" style="font-size:.75rem;color:var(--t2)">${el}s/${tot}s</span></div><div class="ptrack"><div class="pbar" style="width:${p}%"></div></div></div>${sc?`<div style="display:flex;gap:14px"><div><div style="color:var(--t2);font-size:.62rem;text-transform:uppercase">APs</div><div style="font-size:1.1rem;font-weight:700;color:var(--g);font-family:'Orbitron',monospace">${sc.access_points?.length||0}</div></div><div><div style="color:var(--t2);font-size:.62rem;text-transform:uppercase">Clientes</div><div style="font-size:1.1rem;font-weight:700;color:var(--c);font-family:'Orbitron',monospace">${sc.client_count||0}</div></div></div>`:''} ${st==='running'?`<button class="btn btn-d btn-sm" style="width:100%;margin-top:10px" onclick="stopScan()">Detener</button>`:''}`;}async function stopScan(){if(_scan)try{await A.stopScan(_scan.id);toast('Detenido','success');}catch(e){toast(e.message,'error');}}
async function loadScanR(id){try{const sc=await A.getScan(id);ST.lastScan=sc;localStorage.setItem('lastScan',JSON.stringify(sc));renderScanR(sc);}catch(e){toast(e.message,'error');}}
function renderScanR(scan){
  const el=document.getElementById('ws-results');if(!el)return;
  const aps=scan.access_points||[],cli=scan.clients||[],sorted=[...aps].sort((a,b)=>b.power-a.power);
  el.innerHTML=`<div class="card" style="margin-bottom:16px"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;flex-wrap:wrap;gap:8px"><div class="ctitle" style="margin-bottom:0">${ic('wifi')} APs (${aps.length})</div><div style="display:flex;gap:6px;align-items:center"><span class="badge b-c">${scan.band}</span>${stb(scan.status)}${scan.id?`<button class="btn btn-gh btn-sm" onclick="loadPnl('${scan.id}')" title="Analiza las probe requests para detectar candidatos a Evil Twin">${ic('eye',12)} Analizar PNL</button>`:''}</div></div>
  ${!aps.length?`<div class="empty" style="padding:24px">${ic('wifi',32)}<h3>Sin APs</h3></div>`:`<div class="twrap"><table><thead><tr><th>ESSID</th><th>BSSID</th><th>Señal</th><th>CH</th><th>Seguridad</th><th>Fab.</th><th>Cli</th><th>Acciones</th></tr></thead><tbody>
  ${sorted.map(ap=>`<tr><td><div style="display:flex;align-items:center;gap:5px"><strong>${ap.essid||'<oculto>'}</strong>${ap.is_hidden?`<span class="badge b-x" style="font-size:.56rem">OCU</span>`:''}</div></td><td class="mono" style="font-size:.7rem;color:var(--t2)">${ap.bssid}</td><td><div style="display:flex;align-items:center;gap:4px">${sigb(ap.power)}<span class="mono" style="font-size:.66rem;color:var(--t2)">${ap.power}</span></div></td><td class="mono" style="font-weight:600">${ap.channel||'—'}</td><td>${sbadge(ap.security||'?')} ${ap.wps?`<span class="badge b-y" style="font-size:.56rem">WPS</span>`:''}</td><td style="font-size:.7rem;color:var(--t2);max-width:90px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${ap.manufacturer||'—'}</td><td style="font-weight:700;color:${(ap.clients?.length||0)>0?'var(--c)':'var(--t2)'}">${ap.clients?.length||0}</td><td><div style="display:flex;gap:3px"><button class="btn btn-gh btn-xs" title="Handshake" onclick="goHS('${ap.bssid}','${(ap.essid||'').replace(/'/g,"\\'")}',${ap.channel||6})">${ic('key',11)} HS</button><button class="btn btn-gh btn-xs" onclick="showOUI('${ap.bssid}')">OUI</button>${ST.activeSession?`<button class="btn btn-gh btn-xs" onclick="qkF('${ap.bssid}','${(ap.essid||'').replace(/'/g,"\\'")}','${ap.security||'?'}')">${ic('plus',11)}</button>`:''}</div></td></tr>`).join('')}
  </tbody></table></div>`}
  </div>
  <div id="ws-pnl"></div>
  ${cli.length?`<div class="card" style="margin-bottom:16px"><div class="ctitle">${ic('wifi')} Clientes (${cli.length})</div><div class="twrap"><table><thead><tr><th>MAC</th><th>Señal</th><th>AP</th><th>Fabricante</th><th>Probes</th></tr></thead><tbody>${cli.map(c=>`<tr><td class="mono" style="font-size:.76rem">${c.mac}</td><td><div style="display:flex;align-items:center;gap:4px">${sigb(c.power)}<span class="mono" style="font-size:.66rem;color:var(--t2)">${c.power}</span></div></td><td class="mono" style="font-size:.7rem;color:${c.bssid?'var(--c)':'var(--t2)'}">${c.bssid||'No asoc.'}</td><td style="font-size:.7rem;color:var(--t2)">${c.manufacturer||'—'}</td><td style="font-size:.66rem">${(c.probes||[]).slice(0,3).map(p=>`<span class="kbd">${p}</span>`).join(' ')||'—'}</td></tr>`).join('')}</tbody></table></div></div>`:''}`;
}
async function loadPnl(id){const el=document.getElementById('ws-pnl');if(el)el.innerHTML=`<div class="card" style="margin-bottom:16px"><div style="display:flex;align-items:center;gap:8px;color:var(--y)"><div class="spin"></div> Analizando listas de redes preferidas (PNL)...</div></div>`;try{const p=await A.pnl(id);renderPnl(p);}catch(e){toast(e.message,'error');if(el)el.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}}
function renderPnl(p){const el=document.getElementById('ws-pnl');if(!el)return;const cands=p.evil_twin_candidates||[],uniq=p.unique_probed_networks||[],cls=p.clients||[];
  el.innerHTML=`<div class="card card-c" style="margin-bottom:16px"><div class="ctitle">${ic('eye')} Análisis PNL — Inteligencia para Evil Twin</div>
    <div class="hint" style="margin-bottom:12px">${ic('info',11)}Redes que buscan los clientes (probe requests). Las que se buscan pero <b>no se emiten</b> en la zona son candidatas perfectas a Evil Twin: el dispositivo se auto-conectará si emites una con ese nombre.</div>
    <div style="display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap">
      ${[['Clientes',p.total_clients,'var(--c)'],['Asociados',p.associated_clients,'var(--g)'],['Libres',p.unassociated_clients,'var(--y)']].map(([l,v,c])=>`<div style="flex:1;min-width:90px;text-align:center;padding:11px;background:var(--bg3);border-radius:8px;border:1px solid var(--b0)"><div style="font-family:'Orbitron',monospace;font-size:1.4rem;font-weight:700;color:${c}">${v!=null?v:0}</div><div style="font-size:.62rem;color:var(--t2);text-transform:uppercase;margin-top:2px">${l}</div></div>`).join('')}
    </div>
    ${cands.length?`<div style="padding:11px 14px;background:var(--r2);border:1px solid var(--r);border-left:3px solid var(--r);border-radius:var(--r);margin-bottom:12px"><div style="color:var(--r);font-family:'Orbitron',monospace;font-size:.66rem;text-transform:uppercase;letter-spacing:.12em;margin-bottom:7px">${ic('warn',11)} Candidatos a Evil Twin</div>${cands.map(s=>`<div style="color:var(--o);font-size:.8rem;margin-bottom:3px;display:flex;align-items:center;gap:6px"><span>• <strong>"${s}"</strong> — buscada por clientes no asociados</span>${ST.activeSession?'':''}</div>`).join('')}</div>`:`<div class="alert ai" style="margin-bottom:12px">${ic('info')}<div>Sin candidatos claros a Evil Twin en este escaneo.</div></div>`}
    ${uniq.length?`<div style="font-size:.74rem;color:var(--t2);margin-bottom:12px"><strong style="color:var(--t1)">Todas las SSID buscadas:</strong> ${uniq.map(s=>`<span class="kbd">${s}</span>`).join(' ')}</div>`:''}
    ${cls.length?`<div style="font-size:.62rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px">Clientes y sus probes</div>${cls.map(c=>`<div style="padding:9px 12px;background:var(--bg3);border-radius:6px;margin-bottom:6px;border-left:2px solid ${(c.vulnerability_notes||[]).length?'var(--y)':'var(--c)'}"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap"><span class="mono" style="font-size:.76rem;font-weight:600">${c.client_mac}</span><span style="font-size:.72rem;color:var(--p)">${c.manufacturer||'Desconocido'}</span><span class="badge ${c.is_associated?'b-g':'b-x'}">${c.is_associated?'Asociado':'Libre'}</span></div>${(c.probed_networks||[]).length?`<div style="font-size:.7rem;color:var(--t2);margin-top:4px">Busca: ${c.probed_networks.map(s=>`<span class="kbd">${s}</span>`).join(' ')}</div>`:''}${(c.vulnerability_notes||[]).map(n=>`<div style="font-size:.68rem;color:var(--y);margin-top:3px">→ ${n}</div>`).join('')}</div>`).join('')}`:''}
  </div>`;el.scrollIntoView({behavior:'smooth',block:'nearest'});}
function goHS(bssid,essid,ch){setIP({'hs-bssid':bssid,'hs-essid':essid,'hs-ch':ch,'cr-bssid':bssid,'cr-essid':essid});goto('sniffing');}
async function qkF(bssid,essid,sec){if(!ST.activeSession){toast('Activa una sesión primero','warn');return;}if(ST.activeSession.status==='closed'){toast('La sesión activa está cerrada','warn');return;}const sv=sec==='OPEN'?'critical':sec==='WEP'?'high':sec==='WPA'?'medium':'low';const b={session_id:ST.activeSession.id,severity:sv,category:'wifi',title:sec==='OPEN'?'Red WiFi sin cifrado (OPEN)':sec==='WEP'?'Cifrado WEP obsoleto':sec==='WPA'?'WPA v1 obsoleto':'Seguridad WiFi — '+(essid||bssid),description:sec==='OPEN'?`La red "${essid}" (${bssid}) opera sin cifrado. El tráfico puede ser interceptado.`:`Red "${essid}" (${bssid}) usa ${sec}.`,evidence:`BSSID: ${bssid}\nESSID: ${essid||'oculto'}\nSeguridad: ${sec}`,recommendation:sec==='OPEN'?'Configurar WPA3-SAE o WPA2-PSK con contraseña de mínimo 16 caracteres.':sec==='WEP'?'Migrar a WPA2/WPA3 inmediatamente.':'Actualizar a WPA3-SAE si el hardware lo soporta.'};try{await A.addFinding(ST.activeSession.id,b);const u=await A.getSession(ST.activeSession.id).catch(()=>null);if(u)setSession(u);toast(`Hallazgo añadido a "${ST.activeSession.name}"`,'success');}catch(e){toast(e.message,'error');}}
async function showOUI(mac){try{const r=await A.oui(mac);showModal('OUI / Fabricante',`<div style="padding:13px;background:var(--bg0);border-radius:8px;border:1px solid var(--b1);margin-bottom:10px"><div class="mono" style="font-size:1rem;color:var(--c);margin-bottom:7px">${r.mac}</div><div style="font-size:.84rem;margin-bottom:5px"><span style="color:var(--t2)">Fabricante:</span> <strong>${r.manufacturer||'Desconocido'}</strong></div><div style="font-size:.8rem"><span style="color:var(--t2)">OUI:</span> <span class="mono">${r.oui||'—'}</span></div></div>${r.is_randomized?`<div class="alert aw">${ic('warn')}<div>MAC aleatorizada (privacidad)</div></div>`:`<span class="badge b-g">✓ MAC estática</span>`}`,`<button class="btn btn-gh" onclick="closeModal()">Cerrar</button>`);}catch(e){toast(e.message,'error');}}
// ======== RECON ========
async function recon(){
  setC(`<div class="sup"><div class="g2" style="margin-bottom:16px"><div class="card" id="rec-form" data-pp="rec-form">
    <div class="ctitle">${ic('search')} Escaneo nmap</div>
    <div class="frow"><label>Objetivo * <span class="tip" data-tip="IP única (192.168.0.1), rango CIDR (192.168.0.0/24) o rango (192.168.0.1-50). Empieza con un /24 quick para descubrir hosts vivos.">?</span></label><input id="rec-tgt" class="inp" placeholder="192.168.0.0/24" data-p></div>
    <div class="frow"><label>Tipo</label><select id="rec-type" class="inp" onchange="{const w=document.getElementById('rec-custom-wrap');if(w)w.style.display=this.value==='custom'?'block':'none';}">
      <option value="quick">Quick — Ping sweep</option><option value="full">Full — Todos puertos + OS</option>
      <option value="service">Service — Versiones</option><option value="vuln">Vuln — NSE vulnerabilidades</option>
      <option value="os_detect">OS Detect — Fingerprinting</option><option value="stealth">Stealth — SYN scan</option>
      <option value="udp">UDP — Top 100</option><option value="custom">Custom — Argumentos propios</option>
    </select></div>
    <div class="frow" id="rec-custom-wrap" style="display:none"><label>Argumentos nmap <span class="tip" data-tip="Tus propios flags de nmap, ej: -sS -sV -p- -T4 --script vuln. El objetivo se añade automáticamente.">?</span></label><input id="rec-custom" class="inp" placeholder="-sS -sV -p- -T4"></div>
    <div class="frow"><label>Puertos (opcional)</label><input id="rec-ports" class="inp" placeholder="22,80,443"></div>
    <button class="btn btn-g" style="width:100%" id="rec-btn" onclick="startRecon()">${ic('play')} Iniciar</button>
    <div style="font-size:.62rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin:12px 0 6px">Herramientas rápidas</div>
    <div style="display:flex;gap:7px">
      <button class="btn btn-gh btn-sm" style="flex:1" onclick="doArpSweep()">${ic('wifi',12)} ARP Sweep <span class="tip" data-tip="Descubrimiento L2 rápido: envía ARP a todo el rango (usa el Objetivo como CIDR, ej. 192.168.0.0/24). Más rápido que nmap en la LAN y no lo bloquean firewalls.">?</span></button>
      <button class="btn btn-gh btn-sm" style="flex:1" onclick="showRouterProbe()">${ic('shield',12)} Router Probe <span class="tip" data-tip="Auditoría enfocada del gateway: puertos de administración (SSH/Telnet/HTTP/HTTPS), modelo/firmware y credenciales por defecto.">?</span></button>
    </div>
  </div>
  <div class="card" id="rec-st-card">
    <div class="ctitle">${ic('search')} Estado</div>
    <div id="rec-empty" class="empty" style="padding:22px">${ic('search',36)}<h3>Sin escaneo activo</h3></div>
    <div id="rec-live" style="display:none"></div>
  </div></div>
  <div id="rec-results"></div><div id="rec-hist"></div></div>`);
  loadRecHist();const rt=document.getElementById('rec-type'),rw=document.getElementById('rec-custom-wrap');if(rt&&rw)rw.style.display=rt.value==='custom'?'block':'none';}
async function loadRecHist(){try{const sc=await A.listRecon();const el=document.getElementById('rec-hist');if(!el||!sc.length)return;el.innerHTML=`<div style="font-family:'Orbitron',monospace;font-size:.68rem;color:var(--t2);letter-spacing:.1em;text-transform:uppercase;margin-bottom:9px">Escaneos Anteriores</div><div class="twrap"><table><thead><tr><th>Objetivo</th><th>Tipo</th><th>Comando</th><th>Hosts</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>${sc.slice(0,8).map(s=>`<tr><td class="mono">${s.target}</td><td><span class="badge b-c">${s.scan_type}</span></td><td class="mono" style="font-size:.64rem;color:var(--t2);max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${s.command||''}">${s.command||'—'}</td><td><strong>${s.hosts?.length||0}</strong></td><td>${stb(s.status)}</td><td class="mono" style="font-size:.68rem;color:var(--t2)">${fd(s.started_at)}</td><td><button class="btn btn-gh btn-xs" onclick="loadRecR('${s.id}')">Ver</button></td></tr>`).join('')}</tbody></table></div>`;}catch{}}
async function startRecon(){const t=document.getElementById('rec-tgt')?.value?.trim(),tp=document.getElementById('rec-type')?.value,p=document.getElementById('rec-ports')?.value?.trim(),ca=document.getElementById('rec-custom')?.value?.trim();if(!t){toast('Introduce objetivo','warn');return;}if(tp==='custom'&&!ca){toast('Introduce argumentos nmap','warn');return;}const btn=document.getElementById('rec-btn');if(btn)btn.disabled=true;const live=document.getElementById('rec-live'),empty=document.getElementById('rec-empty');if(empty)empty.style.display='none';if(live){live.style.display='block';live.innerHTML=`<div style="display:flex;align-items:center;gap:8px;color:var(--y)"><div class="spin"></div> nmap <strong>${tp}</strong> en <span class="mono">${t}</span>...</div><div class="ptrack" style="margin-top:10px"><div class="pbar ind"></div></div>`;}try{const r=await A.startRecon({target:t,scan_type:tp,ports:p||null,custom_args:tp==='custom'?ca:null,timeout:600});if(live)live.innerHTML=`<div class="alert as">${ic('check')}<div>Completado · ${r.hosts?.length||0} hosts</div></div>${r.command?`<div style="font-size:.7rem;color:var(--t2);margin-top:7px">${ic('terminal',11)} Comando:<div class="mono" style="color:var(--c);font-size:.67rem;margin-top:3px;padding:5px;background:var(--bg0);border-radius:4px;word-break:break-all">${r.command}</div></div>`:''}`;renderRecR(r);loadRecHist();}catch(e){toast(e.message,'error');if(live)live.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}if(btn)btn.disabled=false;}
async function loadRecR(id){try{const r=await A.getRecon(id);renderRecR(r);}catch(e){toast(e.message,'error');}}
async function doArpSweep(){const t=document.getElementById('rec-tgt')?.value?.trim()||'192.168.0.0/24';const live=document.getElementById('rec-live'),empty=document.getElementById('rec-empty');if(empty)empty.style.display='none';if(live){live.style.display='block';live.innerHTML=`<div style="display:flex;align-items:center;gap:8px;color:var(--y)"><div class="spin"></div> ARP sweep en <span class="mono">${t}</span>...</div><div class="ptrack" style="margin-top:10px"><div class="pbar ind"></div></div>`;}try{const r=await A.reconDiscover(t);if(live)live.innerHTML=`<div class="alert as">${ic('check')}<div>ARP sweep completado · ${r.hosts?.length||0} hosts vivos</div></div>`;renderRecR(r);loadRecHist();}catch(e){toast(e.message,'error');if(live)live.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}}
function showRouterProbe(){const tgt=document.getElementById('rec-tgt')?.value?.trim()||'';const ip=/^\d+\.\d+\.\d+\.\d+$/.test(tgt)?tgt:'192.168.0.1';showModal('Router Probe — Auditoría del gateway',`<div class="alert ai">${ic('info')}<div>Escanea los puertos de administración del router e identifica servicios y modelo. Comprometer el gateway suele dar control total de la red.</div></div><div class="frow"><label>IP del router / gateway</label><input id="rp-ip" class="inp" value="${ip}" placeholder="192.168.0.1"></div><div class="crow"><input type="checkbox" id="rp-creds" checked><label for="rp-creds">Comprobar credenciales por defecto (admin/admin…)</label></div><div class="crow"><input type="checkbox" id="rp-vulns" checked><label for="rp-vulns">Comprobar vulnerabilidades conocidas</label></div><div class="crow"><input type="checkbox" id="rp-brute"><label for="rp-brute">Fuerza bruta de credenciales (lento y ruidoso)</label></div><div id="rp-res" style="margin-top:10px"></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-g" onclick="doRouterProbe()">${ic('play')} Escanear</button>`);}
async function doRouterProbe(){const ip=document.getElementById('rp-ip')?.value?.trim()||'192.168.0.1';const el=document.getElementById('rp-res');if(el)el.innerHTML=`<div style="display:flex;align-items:center;gap:7px;color:var(--y)"><div class="spin"></div> Sondeando ${ip}...</div><div class="ptrack" style="margin-top:8px"><div class="pbar ind"></div></div>`;try{const r=await A.reconRouter({target_ip:ip,check_default_creds:document.getElementById('rp-creds')?.checked,check_known_vulns:document.getElementById('rp-vulns')?.checked,brute_force:document.getElementById('rp-brute')?.checked});if(el)el.innerHTML=renderRouterProbe(r);toast(r.reachable?'Router Probe completado':'Router no responde',r.reachable?'success':'warn');}catch(e){toast(e.message,'error');if(el)el.innerHTML=`<div class="alert ae">${ic('x')}<div>${e.message}</div></div>`;}}
function renderRouterProbe(r){if(!r||!r.reachable)return `<div class="alert aw">${ic('warn')}<div><strong>${r?.target||'El objetivo'}</strong> no responde o está filtrado.</div></div>`;const svc=[['SSH (22)',r.ssh_open,false],['Telnet (23)',r.telnet_open,true],['HTTP (80)',r.http_open,false],['HTTPS (443)',r.https_open,false]];return `<div class="alert as" style="margin-bottom:10px">${ic('check')}<div><strong>${r.target}</strong> alcanzable${r.hostname?` · ${r.hostname}`:''}</div></div>
  <div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px">${svc.map(([l,o,danger])=>`<span class="badge ${o?(danger?'b-r':'b-g'):'b-x'}">${o?ic(danger?'warn':'check',10):''} ${l}</span>`).join('')}</div>
  ${r.telnet_open?`<div class="alert aw" style="margin-bottom:8px">${ic('warn')}<div style="font-size:.74rem">Telnet abierto: protocolo inseguro en texto plano. Hallazgo recomendable.</div></div>`:''}
  ${r.os_guess?`<div style="font-size:.75rem;margin-bottom:6px"><span style="color:var(--t2)">OS:</span> <span class="badge b-p">${r.os_guess}</span></div>`:''}
  ${r.mac?`<div style="font-size:.72rem;color:var(--t2);margin-bottom:8px">MAC: <span class="mono">${r.mac}</span></div>`:''}
  ${(r.services||[]).length?`<div style="font-size:.66rem;color:var(--t2);text-transform:uppercase;letter-spacing:.06em;margin-bottom:4px">Servicios detectados</div>${r.services.map(s=>`<div style="font-size:.72rem;color:var(--t1);margin-bottom:2px"><span class="mono" style="color:var(--g)">${s.port}</span> <strong>${s.name||''}</strong> ${s.product||''} ${s.version||''}</div>`).join('')}`:''}
  ${ST.activeSession?`<button class="btn btn-gh btn-sm" style="margin-top:10px" onclick="qkRouterF('${r.target}',${r.telnet_open?1:0})">${ic('plus',11)} Crear hallazgo</button>`:''}`;}
async function qkRouterF(ip,telnet){if(!ST.activeSession){toast('Activa una sesión primero','warn');return;}if(ST.activeSession.status==='closed'){toast('La sesión activa está cerrada','warn');return;}const b={session_id:ST.activeSession.id,severity:telnet?'high':'medium',category:'router',title:`Superficie de administración expuesta en el router ${ip}`,description:`El gateway ${ip} expone servicios de administración en la LAN.${telnet?' Telnet (23) está abierto: credenciales y sesión viajan en texto plano.':''}`,evidence:`Router Probe sobre ${ip}${telnet?'\nPuerto 23/tcp (telnet) ABIERTO':''}`,recommendation:'Restringir el acceso de administración a redes de confianza, deshabilitar Telnet en favor de SSH, cambiar credenciales por defecto y actualizar el firmware.'};try{await A.addFinding(ST.activeSession.id,b);const u=await A.getSession(ST.activeSession.id).catch(()=>null);if(u)setSession(u);toast('Hallazgo del router añadido a la sesión','success');}catch(e){toast(e.message,'error');}}
function renderRecR(scan){
  const el=document.getElementById('rec-results');if(!el)return;const hosts=scan.hosts||[];
  el.innerHTML=`<div class="card" style="margin-bottom:16px"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;flex-wrap:wrap;gap:8px"><div class="ctitle" style="margin-bottom:0">${ic('search')} Hosts (${hosts.length}) · <span class="badge b-c">${scan.scan_type}</span></div>${scan.command?`<div class="mono" style="font-size:.64rem;color:var(--t2);max-width:280px;overflow:hidden;text-overflow:ellipsis" title="${scan.command}">${ic('terminal',11)} ${scan.command}</div>`:''}</div>
  ${!hosts.length?`<div class="empty" style="padding:22px">${ic('search',30)}<h3>Sin hosts</h3></div>`:hosts.map(h=>`<div class="hitem" id="hi-${h.ip.replace(/\./g,'_')}"><div class="hhdr" onclick="togHD('${h.ip}')"><span style="font-family:'JetBrains Mono',monospace;font-size:.9rem;color:var(--c);font-weight:600">${h.ip}</span>${h.hostname?`<span style="font-size:.76rem;color:var(--t2)">${h.hostname}</span>`:''} ${h.mac?`<span class="mono" style="font-size:.7rem;color:var(--t2)">${h.mac}</span>`:''} <span class="badge ${h.state==='up'?'b-g':'b-x'}">${h.state}</span> ${h.os_guess?`<span class="badge b-p">${h.os_guess}</span>`:''} ${h.ports?.length?`<span class="badge b-c">${h.ports.filter(p=>p.state==='open').length} open</span>`:''}<div style="margin-left:auto;display:flex;gap:5px"><button class="btn btn-gh btn-xs" onclick="event.stopPropagation();hScan('${h.ip}','service')" title="Deep scan">${ic('search',11)} Deep</button><button class="btn btn-d btn-xs" onclick="event.stopPropagation();hScan('${h.ip}','vuln')" title="Vuln scan">${ic('warn',11)} Vuln</button></div></div><div class="hdetail" id="hd-${h.ip.replace(/\./g,'_')}" style="display:none">${h.ports?.length?`<div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:7px">${h.ports.map(p=>`<span class="badge ${p.state==='open'?'b-g':'b-x'}" title="${p.service||''}">${p.port}/${p.protocol}</span>`).join('')}</div>`:''} ${h.services?.length?`<div style="margin-bottom:7px">${h.services.map(s=>`<div style="font-size:.72rem;color:var(--t2);margin-bottom:2px"><span class="mono" style="color:var(--g)">${s.port}</span> <strong>${s.name}</strong> ${s.product||''} ${s.version||''}</div>`).join('')}</div>`:''} ${h.scripts?.length?h.scripts.map(s=>`<div style="margin-bottom:6px;padding:7px;background:var(--bg0);border-radius:5px;border-left:2px solid var(--y)"><div style="font-size:.66rem;font-weight:700;color:var(--y);margin-bottom:3px">${ic('warn',10)} ${s.id}</div><pre style="font-size:.64rem;color:var(--t2);white-space:pre-wrap;max-height:200px;overflow-y:auto;line-height:1.4">${s.output}</pre></div>`).join(''):''}  <div id="hs-res-${h.ip.replace(/\./g,'_')}"></div></div></div>`).join('')}
  </div>`;}
function togHD(ip){const k=ip.replace(/\./g,'_'),el=document.getElementById(`hd-${k}`);if(el)el.style.display=el.style.display==='none'?'block':'none';}
async function hScan(ip,type){const k=ip.replace(/\./g,'_'),hd=document.getElementById(`hd-${k}`),res=document.getElementById(`hs-res-${k}`);if(hd)hd.style.display='block';if(res)res.innerHTML=`<div style="display:flex;align-items:center;gap:7px;margin-top:10px;color:var(--y)"><div class="spin"></div> ${type} en ${ip}...</div><div class="ptrack" style="margin-top:5px"><div class="pbar ind"></div></div>`;try{const r=await A.startRecon({target:ip,scan_type:type,timeout:300}),h=r.hosts?.find(x=>x.ip===ip)||r.hosts?.[0];if(res)res.innerHTML=`<div style="margin-top:10px"><div style="font-size:.66rem;color:var(--t2);margin-bottom:5px;text-transform:uppercase;letter-spacing:.06em">Resultado ${type} · ${fd(new Date().toISOString())}</div>${r.command?`<div class="mono" style="font-size:.64rem;color:var(--c);padding:4px 6px;background:var(--bg0);border-radius:4px;margin-bottom:7px;word-break:break-all">${ic('terminal',10)} ${r.command}</div>`:''} ${h?`${h.os_guess?`<div style="margin-bottom:5px"><span class="badge b-p">OS: ${h.os_guess}</span></div>`:''} ${(h.ports||[]).filter(p=>p.state==='open').length?`<div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:6px">${h.ports.filter(p=>p.state==='open').map(p=>`<span class="badge b-g" title="${p.service||''} ${p.version||''}">${p.port}/${p.protocol}</span>`).join('')}</div>`:''} ${(h.services||[]).length?`<div style="margin-bottom:6px">${h.services.map(s=>`<div style="font-size:.7rem;color:var(--t1);margin-bottom:2px"><span class="mono" style="color:var(--g)">${s.port}</span> <strong>${s.name}</strong> ${s.product||''} ${s.version||''}</div>`).join('')}</div>`:''} ${(h.scripts||[]).length?h.scripts.map(s=>`<div style="margin-bottom:7px;padding:7px;background:var(--bg0);border-radius:5px;border-left:3px solid var(--y)"><div style="font-size:.66rem;font-weight:700;color:var(--y);margin-bottom:3px">${ic('warn',10)} ${s.id}</div><pre style="font-size:.63rem;color:var(--t2);white-space:pre-wrap;max-height:200px;overflow-y:auto;line-height:1.4">${s.output}</pre></div>`).join(''):''}`:''}</div>`;toast(`${type} OK para ${ip}`,'success');}catch(e){toast(e.message,'error');if(res)res.innerHTML=`<div class="alert ae" style="margin-top:8px">${ic('x')}<div>${e.message}</div></div>`;}}
