// WFAudit · sesiones — auditorías, hallazgos, evidencias fotográficas, timeline e informes
let _sess=[],_curSes=null,_sesTab='resumen',_fFilter={sev:'',cat:'',q:''},_fSort='sev';
const SEVS=['critical','high','medium','low','info'];
const SEVC={critical:'r',high:'o',medium:'y',low:'g',info:'c'};
const SEVL={critical:'Crítico',high:'Alto',medium:'Medio',low:'Bajo',info:'Info'};
const SEVEMO={critical:'🔴',high:'🟠',medium:'🟡',low:'🟢',info:'🔵'};
function val(id){return document.getElementById(id)?.value||'';}
// Entrada: si hay sesión activa -> su detalle; si no -> lista
async function sessions(){if(ST.activeSession?.id){viewSes(ST.activeSession.id);return;}sessionList();}
async function sessionList(){setC(`<div style="display:flex;align-items:center;gap:10px;color:var(--t2)"><div class="spin"></div> Cargando...</div>`);try{_sess=await A.sessions();}catch(e){setC(`<div class="alert ae">${ic('x')} ${e.message}</div>`);return;}renderSessList();}
function renderSessList(){
  setTB('SESIONES','Gestión de auditorías',`<button class="btn btn-gh btn-sm" onclick="sessionList()">${ic('refresh')} Actualizar</button><button class="btn btn-g btn-sm" onclick="newSessionView()">${ic('plus')} Nueva</button>`);
  if(!_sess.length){setC(`<div class="empty">${ic('folder',48)}<h3>Sin sesiones</h3><p>Crea una sesión para documentar tu auditoría</p><button class="btn btn-g" style="margin-top:12px" onclick="newSessionView()">${ic('plus')} Crear sesión</button></div>`);return;}
  setC(`<div class="sup" style="display:flex;flex-direction:column;gap:11px">${_sess.map(s=>{const a=s.id===ST.activeSession?.id,fi=s.findings||[],cr=fi.filter(f=>f.severity==='critical').length,hi=fi.filter(f=>f.severity==='high').length;return `<div class="card ${a?'card-c glow-c':''}" style="cursor:pointer" onclick="viewSes('${s.id}')"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:10px"><div style="flex:1;min-width:0"><div style="display:flex;align-items:center;gap:8px;margin-bottom:5px;flex-wrap:wrap"><span style="font-family:'Orbitron',monospace;font-size:.9rem;font-weight:700">${s.name}</span>${stb(s.status)}${a?`<span class="badge b-c">▶ ACTIVA</span>`:''}</div><div style="font-size:.75rem;color:var(--t2);margin-bottom:7px">${s.company||'—'} · <strong style="color:var(--t1)">${s.auditor||'—'}</strong> · <span class="mono">${s.id}</span> · ${fd(s.created_at)}</div><div style="display:flex;gap:6px;flex-wrap:wrap"><span class="badge b-x">${fi.length} hallazgos</span>${cr?`<span class="badge b-r">⚠ ${cr} críticos</span>`:''}${hi?`<span class="badge b-o">${hi} altos</span>`:''}</div></div><div style="display:flex;gap:6px;flex-shrink:0" onclick="event.stopPropagation()">${a?`<button class="btn btn-gh btn-sm" onclick="deactSes()">Desactivar</button>`:`<button class="btn btn-gh btn-sm" onclick="actSes('${s.id}')">Activar</button>`}<button class="btn btn-p btn-sm" onclick="viewSes('${s.id}')">Ver →</button><button class="btn btn-d btn-sm btn-ico" title="Eliminar sesión" onclick="delSes('${s.id}','${(s.name||'').replace(/'/g,"\\'").replace(/"/g,'&quot;')}')">${ic('trash',13)}</button></div></div></div>`;}).join('')}</div>`);
}
async function actSes(id){let s=_sess.find(x=>x.id===id)||(_curSes&&_curSes.id===id?_curSes:null);if(!s)s=await A.getSession(id).catch(()=>null);if(s){setSession(s);toast(`"${s.name}" activada`,'success');viewSes(id);}}
function deactSes(){const cur=_curSes;setSession(null);toast('Sin sesión activa','info');if(cur)viewSes(cur.id);else sessionList();}
function delSes(id,name){confirmDlg(`¿Eliminar la sesión <b>«${name}»</b>? Se borrarán <b>todos sus hallazgos y sus fotos de evidencia</b>.`,()=>{confirmDlg(`Esta acción es <b>permanente e irreversible</b>. ¿Confirmas el borrado definitivo de «${name}»?`,async()=>{try{await A.delSession(id);if(ST.activeSession?.id===id)setSession(null);toast('Sesión eliminada','success');sessionList();}catch(e){toast(e.message,'error');}},{ok:'Sí, borrar definitivamente'});},{ok:'Continuar'});}
async function viewSes(id){
  let s;try{s=await A.getSession(id);}catch(e){toast(e.message,'error');return;}
  _curSes=s;ST.section='sessions';
  document.querySelectorAll('.ni').forEach(e=>e.classList.toggle('active',e.dataset.s==='sessions'));
  setTB('SESIÓN',s.name,`<button class="btn btn-gh btn-sm" onclick="sessionList()">← Todas las sesiones</button>`);
  const isA=s.id===ST.activeSession?.id,closed=s.status==='closed',fi=s.findings||[];
  if(isA&&ST.activeSession){ST.activeSession.status=s.status;updateSB();}
  setC(`<div class="sup">
    <div class="card ${isA?'card-c':''}" style="margin-bottom:14px">
      <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap">
        <div style="flex:1;min-width:220px">
          <div style="font-family:'Orbitron',monospace;font-size:1.05rem;font-weight:700;margin-bottom:4px">${s.name}</div>
          <div style="font-size:.76rem;color:var(--t2)">${s.company||'—'} · ${s.auditor||'—'} · <span class="mono">${s.id}</span></div>
          <div style="font-size:.72rem;color:var(--t2);margin-top:3px">Creada ${fd(s.created_at)}${s.closed_at?` · Cerrada ${fd(s.closed_at)}`:''}</div>
          ${s.scope?`<div style="margin-top:8px;font-size:.74rem;color:var(--t1)"><b style="color:var(--t2)">Alcance:</b> ${s.scope}</div>`:''}
          ${s.notes?`<div style="margin-top:6px;font-size:.74rem;color:var(--t1);border-left:2px solid var(--c);padding-left:9px;white-space:pre-wrap">${s.notes}</div>`:''}
        </div>
        <div style="display:flex;gap:7px;flex-wrap:wrap;align-items:center">${stb(s.status)}${isA?`<span class="badge b-c">▶ ACTIVA</span>`:''}${isA?`<button class="btn btn-gh btn-sm" onclick="deactSes()">Desactivar</button>`:`<button class="btn btn-gh btn-sm" onclick="actSes('${s.id}')">Activar</button>`}${closed?`<button class="btn btn-g btn-sm" onclick="reopenSesUI('${s.id}')">${ic('refresh',12)} Reabrir</button>`:`<button class="btn btn-gh btn-sm" onclick="closeSesUI('${s.id}')">Cerrar</button>`}<button class="btn btn-gh btn-sm" onclick="editSessionView('${s.id}')">${ic('edit',12)} Editar</button>${!closed?`<button class="btn btn-g btn-sm" onclick="addFindingModal('${s.id}')">${ic('plus')} Hallazgo</button>`:''}</div>
      </div>
      ${closed?`<div class="hint warn" style="margin-top:10px">${ic('warn',11)}Sesión cerrada: no se pueden añadir hallazgos. Reábrela (con motivo) para seguir documentando.</div>`:''}
      <div id="ses-inline" style="margin-top:10px"></div>
    </div>
    <div class="tabs" id="ses-tabs">
      <div class="tab" data-t="resumen" onclick="showSesTab('resumen')">${ic('report',13)} Resumen</div>
      <div class="tab" data-t="hallazgos" onclick="showSesTab('hallazgos')">${ic('warn',13)} Hallazgos <span class="badge b-x" style="margin-left:3px">${fi.length}</span></div>
      <div class="tab" data-t="timeline" onclick="showSesTab('timeline')">${ic('refresh',13)} Timeline <span class="badge b-x" style="margin-left:3px">${(s.events||[]).length}</span></div>
    </div>
    <div id="ses-body"></div>
  </div>`);
  showSesTab(_sesTab);
}
function showSesTab(tab){_sesTab=tab;document.querySelectorAll('#ses-tabs .tab').forEach(e=>e.classList.toggle('active',e.dataset.t===tab));const b=document.getElementById('ses-body');if(!b||!_curSes)return;b.innerHTML=tab==='hallazgos'?sesHallazgos(_curSes):tab==='timeline'?sesTimeline(_curSes):sesResumen(_curSes);}
function sesResumen(s){
  const fi=s.findings||[],sc={};SEVS.forEach(sv=>sc[sv]=fi.filter(f=>f.severity===sv).length);const total=fi.length;
  const risk=sc.critical?['CRÍTICO','r']:sc.high?['ALTO','o']:sc.medium?['MEDIO','y']:total?['BAJO','g']:['SIN HALLAZGOS','x'];
  const byCat={};fi.forEach(f=>{byCat[f.category]=(byCat[f.category]||0)+1;});
  return `<div class="g2" style="margin-bottom:14px;align-items:start">
    <div class="card"><div class="ctitle">${ic('report')} Resumen de severidad</div>
      <div style="display:flex;gap:8px;margin-bottom:12px">${SEVS.map(sv=>`<div style="flex:1;text-align:center;padding:11px 6px;background:var(--bg3);border-radius:8px;border:1px solid var(--b0)"><div class="sev-${sv}" style="font-family:'Orbitron',monospace;font-size:1.5rem;font-weight:700">${sc[sv]}</div><div style="font-size:.58rem;color:var(--t2);text-transform:uppercase;margin-top:2px">${SEVL[sv]}</div></div>`).join('')}</div>
      ${total?`<div style="display:flex;height:11px;border-radius:6px;overflow:hidden;margin-bottom:11px">${SEVS.filter(sv=>sc[sv]).map(sv=>`<div style="flex:${sc[sv]};background:var(--${SEVC[sv]})" title="${SEVL[sv]}: ${sc[sv]}"></div>`).join('')}</div>`:''}
      <div style="display:flex;align-items:center;justify-content:space-between;padding:11px 14px;background:var(--${risk[1]==='x'?'bg3':risk[1]+'2'});border:1px solid var(--${risk[1]==='x'?'b0':risk[1]});border-radius:8px"><span style="font-size:.68rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em">Nivel de riesgo global</span><span style="font-family:'Orbitron',monospace;font-weight:700;font-size:.95rem;color:var(--${risk[1]==='x'?'t2':risk[1]})">${risk[0]}</span></div>
      <div style="font-size:.76rem;color:var(--t2);margin-top:10px">${total} hallazgo${total!==1?'s':''} · ${(s.events||[]).length} eventos en el timeline</div>
    </div>
    <div class="card"><div class="ctitle">${ic('download')} Informe de auditoría</div>
      <div class="hint" style="margin-bottom:11px">${ic('info',11)}Genera un <b>informe PDF profesional</b>: portada, resumen ejecutivo, índice, todos los hallazgos con evidencias y <b>fotos</b>, y el registro de actividad.</div>
      <a class="btn btn-g" style="width:100%;justify-content:center" href="${A.pdfUrl(s.id)}" target="_blank">${ic('download')} Descargar informe PDF</a>
      <div style="font-size:.62rem;color:var(--t2);text-transform:uppercase;letter-spacing:.08em;margin:16px 0 6px">Por categoría</div>
      ${Object.keys(byCat).length?Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div style="display:flex;align-items:center;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--b0);font-size:.78rem"><span>${CI[c]||'📋'} ${CL[c]||c}</span><span class="badge b-x">${n}</span></div>`).join(''):`<div style="font-size:.76rem;color:var(--t2)">Sin hallazgos aún</div>`}
    </div>
  </div>
  ${(sc.critical||sc.high)?`<div class="card"><div class="ctitle">${ic('warn')} Hallazgos prioritarios</div>${fi.filter(f=>f.severity==='critical'||f.severity==='high').slice(0,6).map(f=>`<div class="fitem" style="cursor:pointer;margin-bottom:6px" onclick="showSesTab('hallazgos')"><div class="fhdr">${sevb(f.severity)}<span class="badge b-x">${CI[f.category]||'📋'} ${CL[f.category]||f.category}</span>${f.cvss?`<span class="badge b-p">CVSS ${f.cvss}</span>`:''}<span class="ftitle">${f.title}</span></div></div>`).join('')}</div>`:total?`<div class="card"><div class="empty" style="padding:26px">${ic('check',34)}<h3>Sin hallazgos críticos ni altos</h3></div></div>`:''}`;
}
function sesHallazgos(s){
  const closed=s.status==='closed',all=s.findings||[],cats=[...new Set(all.map(f=>f.category))];
  let fi=all;if(_fFilter.sev)fi=fi.filter(f=>f.severity===_fFilter.sev);if(_fFilter.cat)fi=fi.filter(f=>f.category===_fFilter.cat);if(_fFilter.q){const q=_fFilter.q.toLowerCase();fi=fi.filter(f=>(f.title||'').toLowerCase().includes(q)||(f.description||'').toLowerCase().includes(q)||(f.evidence||'').toLowerCase().includes(q));}
  const filters=`<div class="card" style="margin-bottom:12px"><div style="display:flex;gap:9px;flex-wrap:wrap;align-items:center"><input class="inp" style="flex:1;min-width:150px" placeholder="Buscar en hallazgos..." value="${(_fFilter.q||'').replace(/"/g,'&quot;')}" oninput="_fFilter.q=this.value;showSesTab('hallazgos')" data-nopersist><div style="display:flex;gap:4px;flex-wrap:wrap"><button class="btn btn-xs ${_fFilter.sev?'btn-gh':'btn-p'}" onclick="_fFilter.sev='';showSesTab('hallazgos')">Todas</button>${SEVS.map(sv=>`<button class="btn btn-xs" style="${_fFilter.sev===sv?`background:var(--${SEVC[sv]}2);color:var(--${SEVC[sv]});border-color:var(--${SEVC[sv]})`:'background:transparent;color:var(--t1);border-color:var(--b0)'}" onclick="_fFilter.sev=_fFilter.sev==='${sv}'?'':'${sv}';showSesTab('hallazgos')">${SEVL[sv]} <span style="opacity:.65">${all.filter(f=>f.severity===sv).length}</span></button>`).join('')}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:8px">${cats.length>1?`<div style="display:flex;gap:4px;flex-wrap:wrap;flex:1"><button class="btn btn-xs ${_fFilter.cat?'btn-gh':'btn-p'}" onclick="_fFilter.cat='';showSesTab('hallazgos')">Todas las categorías</button>${cats.map(c=>`<button class="btn btn-xs ${_fFilter.cat===c?'btn-p':'btn-gh'}" onclick="_fFilter.cat=_fFilter.cat==='${c}'?'':'${c}';showSesTab('hallazgos')">${CI[c]||'📋'} ${CL[c]||c}</button>`).join('')}</div>`:'<div style="flex:1"></div>'}<label style="font-size:.7rem;color:var(--t2);display:flex;align-items:center;gap:5px">Ordenar<select class="inp" style="width:auto;padding:4px 8px;font-size:.74rem" onchange="_fSort=this.value;showSesTab('hallazgos')" data-nopersist><option value="sev" ${_fSort==='sev'?'selected':''}>Por severidad</option><option value="new" ${_fSort==='new'?'selected':''}>Más recientes</option><option value="old" ${_fSort==='old'?'selected':''}>Más antiguos</option></select></label></div></div>`;
  const ts=f=>new Date(f.timestamp||0).getTime();
  let body;
  if(!fi.length){body=`<div class="card"><div class="empty" style="padding:38px">${ic(all.length?'search':'check',40)}<h3>${all.length?'Sin resultados para el filtro':'Sin hallazgos'}</h3>${!all.length&&!closed?`<button class="btn btn-g" style="margin-top:12px" onclick="addFindingModal('${s.id}')">${ic('plus')} Añadir hallazgo</button>`:''}</div></div>`;}
  else if(_fSort==='sev'){body=SEVS.flatMap(sv=>{const gr=fi.filter(f=>f.severity===sv);if(!gr.length)return[];return[`<div style="margin-bottom:14px"><div style="font-size:.68rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--${SEVC[sv]});margin-bottom:8px">${ic('warn',12)} ${SEVL[sv].toUpperCase()} (${gr.length})</div>${gr.map(f=>findingCard(s,f,closed)).join('')}</div>`];}).join('');}
  else{const sorted=[...fi].sort((a,b)=>_fSort==='new'?ts(b)-ts(a):ts(a)-ts(b));body=`<div style="margin-bottom:14px"><div style="font-size:.68rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--t2);margin-bottom:8px">${ic('report',12)} Por fecha de reporte — ${_fSort==='new'?'más recientes primero':'más antiguos primero'} (${sorted.length})</div>${sorted.map(f=>findingCard(s,f,closed)).join('')}</div>`;}
  return filters+body;
}
function findingCard(s,f,closed){const photos=f.photos||[],sc=SEVC[f.severity]||'c';return `<div class="fitem fclick" style="border-left:3px solid var(--${sc});padding:13px 15px" onclick="showFinding('${s.id}','${f.id}')" title="Ver hallazgo completo">
  <div class="fhdr" style="margin-bottom:5px">${sevb(f.severity)}<span class="badge b-x">${CI[f.category]||'📋'} ${CL[f.category]||f.category}</span>${f.cvss?`<span class="badge b-p">CVSS ${f.cvss}</span>`:''}<span class="ftitle" style="font-size:.9rem">${f.title}</span><div style="display:flex;gap:3px;margin-left:auto;flex-shrink:0" onclick="event.stopPropagation()">${!closed?`<button class="btn btn-gh btn-xs btn-ico" title="Editar" onclick="findingModal('${s.id}','${f.id}')">${ic('edit',12)}</button><button class="btn btn-d btn-xs btn-ico" title="Eliminar" onclick="delF('${s.id}','${f.id}')">${ic('trash',12)}</button>`:''}</div></div>
  <div class="fdates">${ic('report',10)} Reportado ${fd(f.timestamp)}${f.updated_at?`&nbsp; · &nbsp;${ic('edit',10)} Editado ${fd(f.updated_at)}`:''}</div>
  ${f.description?`<div class="ftext" style="margin-top:8px">${nl2(f.description)}</div>`:''}
  ${f.evidence?`<div class="flabel">Evidencia</div><div class="fpre">${f.evidence}</div>`:''}
  ${photos.length?`<div class="flabel">Evidencia gráfica</div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:4px" onclick="event.stopPropagation()">${photos.map(p=>`<div class="eph" onclick="lightbox('${A.photoUrl(s.id,f.id,p.id)}','${(p.caption||'').replace(/'/g,"\\'")}')"><img src="${A.photoUrl(s.id,f.id,p.id)}" loading="lazy">${p.caption?`<span class="eph-cap">${p.caption}</span>`:''}</div>`).join('')}</div>`:''}
  ${f.recommendation?`<div class="frec">${ic('info',14)}<div><div class="frec-t">Recomendación</div><div class="frec-b">${nl2(f.recommendation)}</div></div></div>`:''}
  ${photos.length?`<div class="ffoot">${photos.length} foto${photos.length!==1?'s':''} de evidencia</div>`:''}
</div>`;}
function sesTimeline(s){const ev=[...(s.events||[])].reverse();const M={session_created:['plus','g'],finding_added:['plus','g'],finding_updated:['edit','c'],finding_deleted:['trash','r'],photo_added:['eye','p'],session_closed:['x','o'],session_reopened:['refresh','g'],session_updated:['edit','c'],comment:['info','c'],note:['info','y'],correction:['edit','o']};return `<div class="card" style="margin-bottom:12px"><div class="ctitle">${ic('plus')} Añadir comentario / nota / corrección</div><div style="display:flex;gap:7px;align-items:flex-start"><textarea id="ses-comment" class="inp" style="flex:1;min-height:52px" placeholder="Comentario, observación, corrección de un hallazgo..." data-nopersist></textarea><div style="display:flex;flex-direction:column;gap:5px"><select id="ses-comment-type" class="inp" style="width:120px" data-nopersist><option value="comment">💬 Comentario</option><option value="note">📝 Nota</option><option value="correction">✏️ Corrección</option></select><button class="btn btn-g btn-sm" onclick="addComment('${s.id}')">${ic('plus')} Añadir</button></div></div></div><div class="card"><div class="ctitle">${ic('refresh')} Timeline de la sesión (${ev.length})</div>${!ev.length?`<div class="empty" style="padding:24px">${ic('refresh',30)}<h3>Sin eventos</h3></div>`:`<div class="tl">${ev.map(e=>{const m=M[e.type]||['info','c'];const isC=['comment','note','correction'].includes(e.type);return `<div class="tl-i"><div class="tl-dot b-${m[1]}">${ic(m[0],11)}</div><div class="tl-c"><div class="tl-msg">${e.message||e.type}</div><div class="tl-t">${fd(e.timestamp)}${isC?` · <span class="badge b-x" style="font-size:.52rem">${e.type}</span>`:''}${e.reason&&!e.message.includes(e.reason)?` · motivo: ${e.reason}`:''}</div></div></div>`;}).join('')}</div>`}</div>`;}
async function addComment(sid){const t=document.getElementById('ses-comment')?.value?.trim(),ty=document.getElementById('ses-comment-type')?.value||'comment';if(!t){toast('Escribe algo','warn');return;}try{await A.addEvent(sid,ty,t);toast('Añadido al timeline','success');viewSes(sid);}catch(e){toast(e.message,'error');}}
// ─── modal de hallazgo (crear / editar) con fotos y staging ───
let _stagedPhotos=[];
function findingModal(sid,fid){
  _stagedPhotos=[];const s=_curSes;const f=fid&&s?(s.findings||[]).find(x=>x.id===fid):null;const existing=f?.photos||[];
  showModal(fid?'Editar hallazgo':'Nuevo hallazgo',
    `<div class="fgrid"><div class="frow"><label>Severidad *</label><select id="f-sv" class="inp" data-nopersist>${SEVS.map(sv=>`<option value="${sv}" ${(f?f.severity:'medium')===sv?'selected':''}>${SEVEMO[sv]} ${SEVL[sv]}</option>`).join('')}</select></div><div class="frow"><label>Categoría *</label><select id="f-ca" class="inp" data-nopersist>${Object.entries(CI).map(([v,i2])=>`<option value="${v}" ${(f?f.category:'wifi')===v?'selected':''}>${i2} ${CL[v]}</option>`).join('')}</select></div></div>
     <div class="fgrid"><div class="frow" style="flex:2"><label>Título *</label><input id="f-ti" class="inp" value="${(f?.title||'').replace(/"/g,'&quot;')}" placeholder="Título del hallazgo" data-nopersist></div><div class="frow"><label>CVSS <span class="tip" data-tip="Puntuación CVSS v3.1 (0.0–10.0). Opcional.">?</span></label><input id="f-cv" class="inp" value="${(f?.cvss||'').replace(/"/g,'&quot;')}" placeholder="9.1" data-nopersist></div></div>
     <div class="frow"><label>Descripción</label><textarea id="f-de" class="inp" style="min-height:110px" placeholder="Explicación técnica: qué se encontró y por qué es un problema. Incluye BSSIDs, IPs, usuarios..." data-nopersist>${f?.description||''}</textarea></div>
     <div class="frow"><label>Evidencia</label><textarea id="f-ev" class="inp" style="min-height:78px;font-family:'JetBrains Mono',monospace;font-size:.76rem" placeholder="Output de comandos, datos técnicos..." data-nopersist>${f?.evidence||''}</textarea></div>
     <div class="frow"><label>Recomendación</label><textarea id="f-re" class="inp" style="min-height:70px" placeholder="Pasos concretos para remediarlo (referencia NIST/OWASP si aplica)..." data-nopersist>${f?.recommendation||''}</textarea></div>
     <div class="frow" style="margin-bottom:0"><label>Fotos de evidencia <span class="tip" data-tip="Se incluyen en el informe PDF. Puedes añadir varias, incluso antes de crear el hallazgo.">?</span></label>
       <div id="ph-wrap" style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px">${existing.map(p=>`<div class="eph"><img src="${A.photoUrl(sid,fid,p.id)}" onclick="lightbox('${A.photoUrl(sid,fid,p.id)}','${(p.caption||'').replace(/'/g,"\\'")}')"><button class="eph-x" title="Eliminar" onclick="delExistingPhoto(event,'${sid}','${fid}','${p.id}')">×</button></div>`).join('')}<span id="ph-staged" style="display:contents"></span></div>
       <label class="ephz ephz-sm" for="ph-input">${ic('download',18)}<span>Haz clic o suelta imágenes</span><input type="file" id="ph-input" accept="image/*" multiple style="display:none" onchange="stagePhotos(this)"></label>
     </div>`,
    `<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-g" id="f-save" onclick="saveFindingModal('${sid}',${fid?`'${fid}'`:'null'})">${ic('check')} ${fid?'Guardar cambios':'Crear hallazgo'}</button>`,true);
  renderStaged();setTimeout(()=>document.getElementById('f-ti')?.focus(),60);
}
function addFindingModal(sid){findingModal(sid,null);}
function delF(sid,fid){const f=((_curSes&&_curSes.findings)||[]).find(x=>x.id===fid);const t=f?f.title:'este hallazgo';confirmDlg(`¿Eliminar el hallazgo <b>«${t}»</b> y todas sus fotos de evidencia? Esta acción no se puede deshacer.`,async()=>{try{await A.delFinding(sid,fid);toast('Hallazgo eliminado','success');if(ST.activeSession?.id===sid){const u=await A.getSession(sid).catch(()=>null);if(u)setSession(u);}_sesTab='hallazgos';viewSes(sid);}catch(e){toast(e.message,'error');}},{ok:'Sí, eliminar'});}
function stagePhotos(input){[...(input.files||[])].forEach(f=>_stagedPhotos.push(f));input.value='';renderStaged();}
function renderStaged(){const el=document.getElementById('ph-staged');if(!el)return;el.innerHTML=_stagedPhotos.map((f,i)=>`<div class="eph staged"><img src="${URL.createObjectURL(f)}"><span class="eph-cap">nueva</span><button class="eph-x" title="Quitar" onclick="unstagePhoto(${i})">×</button></div>`).join('');}
function unstagePhoto(i){_stagedPhotos.splice(i,1);renderStaged();}
async function delExistingPhoto(ev,sid,fid,pid){try{await A.delPhoto(sid,fid,pid);ev.target.closest('.eph')?.remove();const u=await A.getSession(sid).catch(()=>null);if(u)_curSes=u;toast('Foto eliminada','success');}catch(e){toast(e.message,'error');}}
async function saveFindingModal(sid,fid){const b={session_id:sid,severity:val('f-sv'),category:val('f-ca'),title:val('f-ti').trim(),description:val('f-de').trim(),evidence:val('f-ev').trim(),recommendation:val('f-re').trim(),cvss:val('f-cv').trim()||null};if(!b.title){toast('El título es obligatorio','warn');return;}const btn=document.getElementById('f-save');if(btn){btn.disabled=true;btn.innerHTML='<div class="spin"></div> Guardando...';}try{let realFid=fid;if(fid){await A.updFinding(sid,fid,b);}else{const r=await A.addFinding(sid,b);realFid=r.id;}for(const file of _stagedPhotos){await A.uploadPhoto(sid,realFid,file,'').catch(e=>toast('Foto: '+e.message,'error'));}_stagedPhotos=[];closeModal();toast(fid?'Hallazgo actualizado':'Hallazgo creado','success');if(ST.activeSession?.id===sid){const u=await A.getSession(sid).catch(()=>null);if(u)setSession(u);}_sesTab='hallazgos';viewSes(sid);}catch(e){toast(e.message,'error');if(btn){btn.disabled=false;btn.innerHTML=`${ic('check')} ${fid?'Guardar cambios':'Crear hallazgo'}`;}}}
// ─── detalle de hallazgo (modal de solo lectura, secciones grandes) ───
function showFinding(sid,fid){const s=_curSes;const f=s?(s.findings||[]).find(x=>x.id===fid):null;if(!f)return;const photos=f.photos||[],closed=s.status==='closed';const body=`<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-bottom:16px">${sevb(f.severity)}<span class="badge b-x">${CI[f.category]||'📋'} ${CL[f.category]||f.category}</span>${f.cvss?`<span class="badge b-p">CVSS ${f.cvss}</span>`:''}<span class="badge b-x">${ic('report',9)} ${fd(f.timestamp)}</span>${f.updated_at?`<span class="badge b-x">${ic('edit',9)} editado ${fd(f.updated_at)}</span>`:''}</div>${f.description?`<div class="fdlabel">Descripción</div><div class="fdbody">${nl2(f.description)}</div>`:''}${f.evidence?`<div class="fdlabel">Evidencia</div><div class="fpre" style="max-height:none;font-size:.78rem">${f.evidence}</div>`:''}${photos.length?`<div class="fdlabel">Evidencia gráfica</div><div style="display:flex;gap:9px;flex-wrap:wrap;margin-bottom:4px">${photos.map(p=>`<div class="eph big" onclick="lightbox('${A.photoUrl(sid,fid,p.id)}','${(p.caption||'').replace(/'/g,"\\'")}')"><img src="${A.photoUrl(sid,fid,p.id)}">${p.caption?`<span class="eph-cap">${p.caption}</span>`:''}</div>`).join('')}</div>`:''}${f.recommendation?`<div class="frec" style="margin-top:14px">${ic('info',14)}<div><div class="frec-t">Recomendación</div><div class="frec-b">${nl2(f.recommendation)}</div></div></div>`:''}`;showModal(f.title,body,`<button class="btn btn-gh" onclick="closeModal()">Cerrar</button>${!closed?`<button class="btn btn-p" onclick="closeModal();findingModal('${sid}','${fid}')">${ic('edit')} Editar</button>`:''}`,true);}
// ─── cierre / reapertura (modal con confirmación / motivo) ───
function closeSesUI(id){const nm=(_curSes&&_curSes.id===id?_curSes.name:'')||'esta sesión';showModal('Cerrar sesión',`<div class="alert aw" style="margin-bottom:14px">${ic('warn')}<div>Vas a cerrar <strong>${nm}</strong>. Una sesión cerrada <b>no admite nuevos hallazgos</b> hasta que la reabras (indicando un motivo).</div></div><div class="frow" style="margin-bottom:0"><label>Motivo del cierre (opcional)</label><input id="close-reason" class="inp" placeholder="p.ej. auditoría finalizada" data-nopersist></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-d" onclick="doCloseSes('${id}')">${ic('check')} Cerrar sesión</button>`,false);setTimeout(()=>document.getElementById('close-reason')?.focus(),60);}
async function doCloseSes(id){const r=document.getElementById('close-reason')?.value?.trim();try{await A.closeSession(id,r);closeModal();toast('Sesión cerrada','success');if(ST.activeSession?.id===id){ST.activeSession.status='closed';updateSB();}viewSes(id);}catch(e){toast(e.message,'error');}}
function reopenSesUI(id){const nm=(_curSes&&_curSes.id===id?_curSes.name:'')||'esta sesión';showModal('Reabrir sesión',`<div class="alert ai" style="margin-bottom:14px">${ic('info')}<div>Vas a reabrir <strong>${nm}</strong>. Indica el <b>motivo</b> — quedará registrado en el timeline y en el informe.</div></div><div class="frow" style="margin-bottom:0"><label>Motivo de la reapertura *</label><input id="reopen-reason" class="inp" placeholder="p.ej. faltaba documentar un hallazgo" data-nopersist></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-g" onclick="doReopenSes('${id}')">${ic('refresh')} Reabrir sesión</button>`,false);setTimeout(()=>document.getElementById('reopen-reason')?.focus(),60);}
async function doReopenSes(id){const r=document.getElementById('reopen-reason')?.value?.trim();if(!r){toast('El motivo es obligatorio','warn');return;}try{await A.reopenSession(id,r);closeModal();toast('Sesión reabierta','success');if(ST.activeSession?.id===id){ST.activeSession.status='active';updateSB();}viewSes(id);}catch(e){toast(e.message,'error');}}
// ─── crear / editar sesión (modal) ───
function newSessionView(){sessionModal(null);}
function editSessionView(id){sessionModal(id);}
function sessionModal(id){const s=id?((_curSes&&_curSes.id===id)?_curSes:_sess.find(x=>x.id===id)):null;showModal(id?'Editar sesión':'Nueva sesión de auditoría',`<div class="frow"><label>Nombre de la auditoría *</label><input id="s-name" class="inp" value="${(s?.name||'').replace(/"/g,'&quot;')}" placeholder="Auditoría ACME Q4 2026" data-nopersist></div><div class="fgrid"><div class="frow"><label>Empresa / Cliente</label><input id="s-co" class="inp" value="${(s?.company||'').replace(/"/g,'&quot;')}" placeholder="ACME S.L." data-nopersist></div><div class="frow"><label>Auditor</label><input id="s-au" class="inp" value="${(s?.auditor||'').replace(/"/g,'&quot;')}" placeholder="Tu nombre" data-nopersist></div></div><div class="frow"><label>Alcance <span class="tip" data-tip="Redes/activos autorizados, fechas y restricciones del engagement.">?</span></label><textarea id="s-sc" class="inp" style="min-height:130px" placeholder="Redes/activos autorizados, fechas, restricciones..." data-nopersist>${s?.scope||''}</textarea></div><div class="frow" style="margin-bottom:0"><label>Notas</label><textarea id="s-no" class="inp" style="min-height:130px" placeholder="Notas del engagement..." data-nopersist>${s?.notes||''}</textarea></div>`,`<button class="btn btn-gh" onclick="closeModal()">Cancelar</button><button class="btn btn-g" onclick="saveSes(${id?`'${id}'`:'null'})">${ic('check')} ${id?'Guardar cambios':'Crear sesión'}</button>`,true);setTimeout(()=>document.getElementById('s-name')?.focus(),60);}
async function saveSes(id){const b={name:val('s-name').trim(),company:val('s-co').trim(),auditor:val('s-au').trim(),scope:val('s-sc').trim(),notes:val('s-no').trim()};if(!b.name){toast('El nombre es obligatorio','warn');return;}try{if(id){await A.updSession(id,b);if(ST.activeSession?.id===id){const u=await A.getSession(id).catch(()=>null);if(u)setSession(u);}closeModal();toast('Sesión actualizada','success');viewSes(id);}else{const s=await A.createSession(b);closeModal();setSession(s);toast(`"${s.name}" creada`,'success');viewSes(s.id);}}catch(e){toast(e.message,'error');}}
// ─── visor de imágenes (lightbox) ───
function lightbox(url,caption){document.getElementById('lbr').innerHTML=`<div class="lb" onclick="closeLb()"><img src="${url}" onclick="event.stopPropagation()">${caption?`<div class="lb-cap">${caption}</div>`:''}<button class="lb-x" onclick="closeLb()">×</button></div>`;}
function closeLb(){const el=document.getElementById('lbr');if(el)el.innerHTML='';}
// ======== INTERFACES ========
